### ISSUE TITLE
[Bug]: mp4 file deleted if size exceed 50MB

### ISSUE THREAD

**Issue by CODeRUS** [nlef/moonraker-telegram-bot#117]
### What happened and in what context?

i have `cleanup: true` in config
timelapse is bigger than 50MB
got message i should grab it from folder myself
but no mp4 here
but a lot of webp
imo cleanup could delete webp but preserve mp4 if not sent by any conditions

### What branch does this occur on?

development

### Reports only on latest master or development branches!

- [X] I have updated to latest development/master version before submitting the bug

**Comment by nlef** [comment]
@CODeRUS pls check fix)

**Comment by CODeRUS** [comment]
works fine
