### ISSUE TITLE
File Upload to Printer through Telegram

### ISSUE THREAD

**Issue by coldyoungguy** [nlef/moonraker-telegram-bot#118]
### What would you like to see added?

As per the title, i think it would be cool if i can start my prints remotely using telegram, as such to be able to upload a gcode file from telegram would make remote printing a lot easier

**Comment by coldyoungguy** [comment]
I realised its already implemented, abeit, i needed to read the code to find out how to upload

**Comment by nlef** [comment]
@aka13-404 maybe we should add some info about uploading gcodes into wiki)
