### ISSUE TITLE
Config for file upload path

### ISSUE THREAD

**Issue by Pastitas** [nlef/moonraker-telegram-bot#127]
### What would you like to see added?

Add an option on the config for the path that the files are uploaded to.
This could also be achieved by having a dedicated file upload command that asks for a path and then listens for gcode files to be uploaded.

**Comment by aka13-404** [comment]
Could you expand a bit on the usecase, how you intend on using this? Do you really want a specific folder for tg uploads only, or do you generally place all g-code into different folders?

**Comment by Pastitas** [comment]
Yes, I have and make use of a folder structure with klipper. Having at least the option to select which folder everything uploaded by the bot goes to would be great.

**Comment by nlef** [comment]
@Pastitas 
configuration param "upload_path" added. pls test this.
