### ISSUE TITLE
[Bug]: Refreshing status in Telegram after remove history.

### ISSUE THREAD

**Issue by gcastle2007** [nlef/moonraker-telegram-bot#132]
### What happened and in what context?

Запускаем печать. В чат бота приходит сообщение статуса с фотографией. 
Через какое-то время я почистил полностью историю чата, при это удалилось статусное сообщение. Судя по всему, бот отправляет информацию, но она не отображается в чате. Помогает только перезапуск бота.

telegram.log > https://cloud.mail.ru/public/up6F/wW2Qb7t2s

### What branch does this occur on?

master

### Reports only on latest master or development branches!

- [X] I have updated to latest development/master version before submitting the bug

**Comment by aka13-404** [comment]
В целом нет возможности в апи улавливать момент, что удалено обновляемое сообщение.
До изменения АПИ чиниться не будет.
