### ISSUE TITLE
[Bug]: Multiple timelapse merged if printing same file multiple times

### ISSUE THREAD

**Issue by CODeRUS** [nlef/moonraker-telegram-bot#133]
### What happened and in what context?

printed same file multiple times
next time after finished printing old one

### If needed, paste the relevant bot log contents here.

sent to private

### What branch does this occur on?

development

### Reports only on latest master or development branches!

- [X] I have updated to latest development/master version before submitting the bug

**Comment by aka13-404** [comment]
Can not confirm, each print gets ms timestamp
