### ISSUE TITLE
Options for frame resolution if using camera device directly

### ISSUE THREAD

**Issue by CODeRUS** [nlef/moonraker-telegram-bot#136]
### What would you like to see added?

cv2 VideoRecorder have default resolution of 640x480
after calling open function it is useful to add

```
set(cv2.CAP_PROP_FRAME_WIDTH, width)
set(cv2.CAP_PROP_FRAME_HEIGHT, height)
```

**Comment by aka13-404** [comment]
Is working on dev, undcoumented. 
Needs further testing.
