### ISSUE TITLE
[Bug]: openCV queue problem

### ISSUE THREAD

**Issue by ppcd9220** [nlef/moonraker-telegram-bot#149]
### What happened and in what context?

When timelapse by layer height activated, and I issue /video or /status command, sometimes bot produce "No video" (nothing is sent) and "no video" in status.
Looking at logs it loos like there is no queue management with timelapse task (save pic) and sent to telegram.
Looking at forums I see comments that such bug could happen when you try to open camera twice or more times.
There probably should be some queue organized or at lease busy flag.

As a result: No video, no photo in status, and timelapse images are 10kb (empty) or corrupted.
After some time (probably there is a timeout somewhere) without additional concurrent requests it starts working again.

Latest Master release.
Orange Pi Zero 512
Ubuntu Focal.

### If needed, paste the relevant bot log contents here.

2022-05-09 21:13:47,479 - __main__ - ERROR - Exception while handling an update:
Traceback (most recent call last):
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.8/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.8/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "/home/pi/moonraker-telegram-bot/bot/main.py", line 212, in get_video
    with cameraWrap.take_video_generator() as (video_bio, thumb_bio, width, height):
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/pi/moonraker-telegram-bot/bot/camera.py", line 302, in take_video_generator
    (video_bio, thumb_bio, width, height) = self.take_video()
  File "/home/pi/moonraker-telegram-bot/bot/camera.py", line 42, in wrapper
    result = func(self, *args, **kwargs)
  File "/home/pi/moonraker-telegram-bot/bot/camera.py", line 364, in take_video
    height, width, channels = frame.shape
AttributeError: 'NoneType' object has no attribute 'shape'
2022-05-09 21:19:33,312 - camera - WARNING - Reading video frames queue exception 
2022-05-09 21:19:38,294 - camera - WARNING - Writing video frames queue exception <built-in method with_traceback of Full object at 0xa5299208>
2022-05-09 22:20:22,918 - __main__ - ERROR - Exception while handling an update:
Traceback (most recent call last):
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.8/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.8/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "/home/pi/moonraker-telegram-bot/bot/main.py", line 212, in get_video
    with cameraWrap.take_video_generator() as (video_bio, thumb_bio, width, height):
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/pi/moonraker-telegram-bot/bot/camera.py", line 302, in take_video_generator
    (video_bio, thumb_bio, width, height) = self.take_video()
  File "/home/pi/moonraker-telegram-bot/bot/camera.py", line 42, in wrapper
    result = func(self, *args, **kwargs)
  File "/home/pi/moonraker-telegram-bot/bot/camera.py", line 364, in take_video
    height, width, channels = frame.shape
AttributeError: 'NoneType' object has no attribute 'shape'
2022-05-09 22:22:26,001 - __main__ - ERROR - Exception while handling an update:
Traceback (most recent call last):
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.8/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.8/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "/home/pi/moonraker-telegram-bot/bot/main.py", line 212, in get_video
    with cameraWrap.take_video_generator() as (video_bio, thumb_bio, width, height):
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/pi/moonraker-telegram-bot/bot/camera.py", line 302, in take_video_generator
    (video_bio, thumb_bio, width, height) = self.take_video()
  File "/home/pi/moonraker-telegram-bot/bot/camera.py", line 42, in wrapper
    result = func(self, *args, **kwargs)
  File "/home/pi/moonraker-telegram-bot/bot/camera.py", line 364, in take_video
    height, width, channels = frame.shape
AttributeError: 'NoneType' object has no attribute 'shape'
2022-05-09 23:02:06,545 - __main__ - ERROR - Exception while handling an update:
Traceback (most recent call last):
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.8/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.8/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "/home/pi/moonraker-telegram-bot/bot/main.py", line 212, in get_video
    with cameraWrap.take_video_generator() as (video_bio, thumb_bio, width, height):
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/pi/moonraker-telegram-bot/bot/camera.py", line 302, in take_video_generator
    (video_bio, thumb_bio, width, height) = self.take_video()
  File "/home/pi/moonraker-telegram-bot/bot/camera.py", line 42, in wrapper
    result = func(self, *args, **kwargs)
  File "/home/pi/moonraker-telegram-bot/bot/camera.py", line 364, in take_video
    height, width, channels = frame.shape
AttributeError: 'NoneType' object has no attribute 'shape'

### If needed, paste the relevant bot journal contents here.

-- Logs begin at Mon 2022-05-09 18:20:30 MSK, end at Mon 2022-05-09 23:45:14 MSK. --
May 09 23:13:49 orangepizero python[988]: [h264 @ 0xa338aba0] error while decoding MB 68 0, bytestream -5
May 09 23:06:43 orangepizero python[988]: [h264 @ 0xa338aba0] error while decoding MB 69 0, bytestream -17
May 09 23:03:40 orangepizero python[988]: [h264 @ 0xa338aba0] error while decoding MB 56 2, bytestream -23
May 09 23:02:06 orangepizero python[988]: AttributeError: 'NoneType' object has no attribute 'shape'
May 09 23:02:06 orangepizero python[988]:     height, width, channels = frame.shape
May 09 23:02:06 orangepizero python[988]:   File "/home/pi/moonraker-telegram-bot/bot/camera.py", line 364, in take_video
May 09 23:02:06 orangepizero python[988]:     result = func(self, *args, **kwargs)
May 09 23:02:06 orangepizero python[988]:   File "/home/pi/moonraker-telegram-bot/bot/camera.py", line 42, in wrapper
May 09 23:02:06 orangepizero python[988]:     (video_bio, thumb_bio, width, height) = self.take_video()
May 09 23:02:06 orangepizero python[988]:   File "/home/pi/moonraker-telegram-bot/bot/camera.py", line 302, in take_video_generator
May 09 23:02:06 orangepizero python[988]:     return next(self.gen)
May 09 23:02:06 orangepizero python[988]:   File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
May 09 23:02:06 orangepizero python[988]:     with cameraWrap.take_video_generator() as (video_bio, thumb_bio, width, height):
May 09 23:02:06 orangepizero python[988]:   File "/home/pi/moonraker-telegram-bot/bot/main.py", line 212, in get_video
May 09 23:02:06 orangepizero python[988]:     return self.callback(update, context)
May 09 23:02:06 orangepizero python[988]:   File "/home/pi/moonraker-telegram-bot-env/lib/python3.8/site-packages/telegram/ext/handler.py", line 198, in handle_update
May 09 23:02:06 orangepizero python[988]:     handler.handle_update(update, self, check, context)
May 09 23:02:06 orangepizero python[988]:   File "/home/pi/moonraker-telegram-bot-env/lib/python3.8/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
May 09 23:02:06 orangepizero python[988]: Traceback (most recent call last):
May 09 23:02:06 orangepizero python[988]: 2022-05-09 23:02:06,545 - __main__ - ERROR - Exception while handling an update:
May 09 23:02:06 orangepizero python[988]: [h264 @ 0x9e4a82c0] error while decoding MB 18 4, bytestream -23
May 09 23:00:35 orangepizero python[988]: [h264 @ 0xa338aba0] error while decoding MB 68 0, bytestream -7
May 09 23:00:35 orangepizero python[988]: [h264 @ 0xa338aba0] top block unavailable for requested intra mode -1
May 09 22:43:13 orangepizero python[988]: [h264 @ 0xa338aba0] error while decoding MB 69 0, bytestream -13
May 09 22:31:04 orangepizero python[988]: [h264 @ 0xa338aba0] error while decoding MB 64 0, bytestream -7
May 09 22:29:05 orangepizero python[988]: [h264 @ 0xa338aba0] error while decoding MB 62 0, bytestream -7
May 09 22:26:01 orangepizero python[988]: [h264 @ 0xa338aba0] error while decoding MB 68 0, bytestream -9
May 09 22:22:57 orangepizero python[988]: [h264 @ 0xa338aba0] error while decoding MB 70 0, bytestream -5
May 09 22:22:26 orangepizero python[988]: AttributeError: 'NoneType' object has no attribute 'shape'
May 09 22:22:26 orangepizero python[988]:     height, width, channels = frame.shape
May 09 22:22:26 orangepizero python[988]:   File "/home/pi/moonraker-telegram-bot/bot/camera.py", line 364, in take_video
May 09 22:22:26 orangepizero python[988]:     result = func(self, *args, **kwargs)
May 09 22:22:26 orangepizero python[988]:   File "/home/pi/moonraker-telegram-bot/bot/camera.py", line 42, in wrapper
May 09 22:22:26 orangepizero python[988]:     (video_bio, thumb_bio, width, height) = self.take_video()
May 09 22:22:26 orangepizero python[988]:   File "/home/pi/moonraker-telegram-bot/bot/camera.py", line 302, in take_video_generator
May 09 22:22:26 orangepizero python[988]:     return next(self.gen)
May 09 22:22:26 orangepizero python[988]:   File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
May 09 22:22:26 orangepizero python[988]:     with cameraWrap.take_video_generator() as (video_bio, thumb_bio, width, height):
May 09 22:22:26 orangepizero python[988]:   File "/home/pi/moonraker-telegram-bot/bot/main.py", line 212, in get_video
May 09 22:22:26 orangepizero python[988]:     return self.callback(update, context)
May 09 22:22:26 orangepizero python[988]:   File "/home/pi/moonraker-telegram-bot-env/lib/python3.8/site-packages/telegram/ext/handler.py", line 198, in handle_update
May 09 22:22:26 orangepizero python[988]:     handler.handle_update(update, self, check, context)
May 09 22:22:26 orangepizero python[988]:   File "/home/pi/moonraker-telegram-bot-env/lib/python3.8/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
May 09 22:22:26 orangepizero python[988]: Traceback (most recent call last):
May 09 22:22:26 orangepizero python[988]: 2022-05-09 22:22:26,001 - __main__ - ERROR - Exception while handling an update:
May 09 22:20:22 orangepizero python[988]: AttributeError: 'NoneType' object has no attribute 'shape'
May 09 22:20:22 orangepizero python[988]:     height, width, channels = frame.shape
May 09 22:20:22 orangepizero python[988]:   File "/home/pi/moonraker-telegram-bot/bot/camera.py", line 364, in take_video
May 09 22:20:22 orangepizero python[988]:     result = func(self, *args, **kwargs)
May 09 22:20:22 orangepizero python[988]:   File "/home/pi/moonraker-telegram-bot/bot/camera.py", line 42, in wrapper
May 09 22:20:22 orangepizero python[988]:     (video_bio, thumb_bio, width, height) = self.take_video()
May 09 22:20:22 orangepizero python[988]:   File "/home/pi/moonraker-telegram-bot/bot/camera.py", line 302, in take_video_generator
May 09 22:20:22 orangepizero python[988]:     return next(self.gen)
May 09 22:20:22 orangepizero python[988]:   File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
May 09 22:20:22 orangepizero python[988]:     with cameraWrap.take_video_generator() as (video_bio, thumb_bio, width, height):
May 09 22:20:22 orangepizero python[988]:   File "/home/pi/moonraker-telegram-bot/bot/main.py", line 212, in get_video
May 09 22:20:22 orangepizero python[988]:     return self.callback(update, context)
May 09 22:20:22 orangepizero python[988]:   File "/home/pi/moonraker-telegram-bot-env/lib/python3.8/site-packages/telegram/ext/handler.py", line 198, in handle_update
May 09 22:20:22 orangepizero python[988]:     handler.handle_update(update, self, check, context)
May 09 22:20:22 orangepizero python[988]:   File "/home/pi/moonraker-telegram-bot-env/lib/python3.8/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
May 09 22:20:22 orangepizero python[988]: Traceback (most recent call last):
May 09 22:20:22 orangepizero python[988]: 2022-05-09 22:20:22,918 - __main__ - ERROR - Exception while handling an update:
May 09 22:14:43 orangepizero python[988]: [h264 @ 0xa338aba0] error while decoding MB 59 0, bytestream -11
May 09 22:14:43 orangepizero python[988]: [h264 @ 0xa338aba0] top block unavailable for requested intra mode -1
May 09 22:11:38 orangepizero python[988]: [h264 @ 0xa338aba0] error while decoding MB 58 0, bytestream -7
May 09 22:09:34 orangepizero python[988]: [h264 @ 0xa338aba0] error while decoding MB 73 0, bytestream -7
May 09 22:06:31 orangepizero python[988]: [h264 @ 0xa338aba0] error while decoding MB 70 0, bytestream -23
May 09 22:03:26 orangepizero python[988]: [h264 @ 0xa338aba0] error while decoding MB 67 0, bytestream -47
May 09 22:01:24 orangepizero python[988]: [h264 @ 0xa338aba0] error while decoding MB 0 4, bytestream 7165
May 09 22:01:24 orangepizero python[988]: [h264 @ 0xa338aba0] left block unavailable for requested intra mode
May 09 21:58:20 orangepizero python[988]: [h264 @ 0xa338aba0] error while decoding MB 1 6, bytestream -11
May 09 21:58:04 orangepizero python[988]: [h264 @ 0xa338aba0] error while decoding MB 0 6, bytestream 17558
May 09 21:58:04 orangepizero python[988]: [h264 @ 0xa338aba0] left block unavailable for requested intra mode
May 09 21:52:07 orangepizero python[988]: [h264 @ 0xa338aba0] error while decoding MB 6 3, bytestream -7
May 09 21:50:51 orangepizero python[988]: [h264 @ 0xa33d4340] error while decoding MB 67 27, bytestream -7
May 09 21:50:48 orangepizero python[988]: [h264 @ 0xa338aba0] error while decoding MB 38 11, bytestream -5
May 09 21:50:48 orangepizero python[988]: [h264 @ 0xa338aba0] error while decoding MB 67 27, bytestream -7
May 09 21:50:05 orangepizero python[988]: [h264 @ 0xa338aba0] error while decoding MB 72 6, bytestream -7
May 09 21:19:38 orangepizero python[988]: 2022-05-09 21:19:38,294 - camera - WARNING - Writing video frames queue exception <built-in method with_traceback of Full object at 0xa5299208>
May 09 21:19:33 orangepizero python[988]: 2022-05-09 21:19:33,312 - camera - WARNING - Reading video frames queue exception
May 09 21:19:33 orangepizero python[988]: OpenCV: FFMPEG: fallback to use tag 0x31637661/'avc1'
May 09 21:19:33 orangepizero python[988]: OpenCV: FFMPEG: tag 0x34363278/'x264' is not supported with codec id 27 and format 'mp4 / MP4 (MPEG-4 Part 14)'
May 09 21:18:52 orangepizero python[988]: [h264 @ 0xa332f340] error while decoding MB 0 4, bytestream 37055
May 09 21:18:52 orangepizero python[988]: [h264 @ 0xa332f340] left block unavailable for requested intra4x4 mode -1
May 09 21:18:51 orangepizero python[988]: [h264 @ 0xa338aba0] error while decoding MB 0 4, bytestream 37055
May 09 21:18:51 orangepizero python[988]: [h264 @ 0xa338aba0] left block unavailable for requested intra4x4 mode -1
May 09 21:18:04 orangepizero python[988]: [h264 @ 0xa338aba0] error while decoding MB 0 5, bytestream 22137
May 09 21:18:04 orangepizero python[988]: [h264 @ 0xa338aba0] left block unavailable for requested intra4x4 mode -1
May 09 21:16:31 orangepizero python[988]: [h264 @ 0xa33048e0] error while decoding MB 14 43, bytestream -19
May 09 21:16:01 orangepizero python[988]: [h264 @ 0xa33c3240] error while decoding MB 0 5, bytestream 17241
May 09 21:16:01 orangepizero python[988]: [h264 @ 0xa33c3240] left block unavailable for requested intra mode
May 09 21:15:58 orangepizero python[988]: [h264 @ 0xa33048e0] error while decoding MB 0 5, bytestream 17241
May 09 21:15:58 orangepizero python[988]: [h264 @ 0xa33048e0] left block unavailable for requested intra mode
May 09 21:15:09 orangepizero python[988]: [h264 @ 0xa33048e0] error while decoding MB 51 4, bytestream -21
May 09 21:13:47 orangepizero python[988]: AttributeError: 'NoneType' object has no attribute 'shape'
May 09 21:13:47 orangepizero python[988]:     height, width, channels = frame.shape
May 09 21:13:47 orangepizero python[988]:   File "/home/pi/moonraker-telegram-bot/bot/camera.py", line 364, in take_video
May 09 21:13:47 orangepizero python[988]:     result = func(self, *args, **kwargs)
May 09 21:13:47 orangepizero python[988]:   File "/home/pi/moonraker-telegram-bot/bot/camera.py", line 42, in wrapper
May 09 21:13:47 orangepizero python[988]:     (video_bio, thumb_bio, width, height) = self.take_video()
May 09 21:13:47 orangepizero python[988]:   File "/home/pi/moonraker-telegram-bot/bot/camera.py", line 302, in take_video_generator
May 09 21:13:47 orangepizero python[988]:     return next(self.gen)
May 09 21:13:47 orangepizero python[988]:   File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
May 09 21:13:47 orangepizero python[988]:     with cameraWrap.take_video_generator() as (video_bio, thumb_bio, width, height):
May 09 21:13:47 orangepizero python[988]:   File "/home/pi/moonraker-telegram-bot/bot/main.py", line 212, in get_video
May 09 21:13:47 orangepizero python[988]:     return self.callback(update, context)
May 09 21:13:47 orangepizero python[988]:   File "/home/pi/moonraker-telegram-bot-env/lib/python3.8/site-packages/telegram/ext/handler.py", line 198, in handle_update
May 09 21:13:47 orangepizero python[988]:     handler.handle_update(update, self, check, context)
May 09 21:13:47 orangepizero python[988]:   File "/home/pi/moonraker-telegram-bot-env/lib/python3.8/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
May 09 21:13:47 orangepizero python[988]: Traceback (most recent call last):
May 09 21:13:47 orangepizero python[988]: 2022-05-09 21:13:47,479 - __main__ - ERROR - Exception while handling an update:
May 09 21:13:47 orangepizero python[988]: [h264 @ 0xa5b24760] error while decoding MB 37 15, bytestream -7
May 09 21:13:39 orangepizero python[988]: [h264 @ 0xa5b24760] error while decoding MB 0 11, bytestream 16436
May 09 21:13:39 orangepizero python[988]: [h264 @ 0xa5b24760] left block unavailable for requested intra4x4 mode -1
May 09 21:13:07 orangepizero python[988]: [h264 @ 0xa33048e0] error while decoding MB 0 7, bytestream 5787
May 09 21:13:07 orangepizero python[988]: [h264 @ 0xa33048e0] left block unavailable for requested intra mode
May 09 21:10:03 orangepizero python[988]: [h264 @ 0xa33048e0] error while decoding MB 48 3, bytestream -19
May 09 21:07:46 orangepizero python[988]: [h264 @ 0xa33bceb0] error while decoding MB 0 5, bytestream 23996
May 09 21:07:46 orangepizero python[988]: [h264 @ 0xa33bceb0] left block unavailable for requested intra mode
May 09 21:07:40 orangepizero python[988]: [h264 @ 0xa33048e0] error while decoding MB 0 5, bytestream 23996
May 09 21:07:40 orangepizero python[988]: [h264 @ 0xa33048e0] left block unavailable for requested intra mode
May 09 21:06:33 orangepizero python[988]: [h264 @ 0xa33048e0] error while decoding MB 0 23, bytestream 4707
May 09 21:06:33 orangepizero python[988]: [h264 @ 0xa33048e0] left block unavailable for requested intra4x4 mode -1
May 09 21:04:34 orangepizero python[988]: [h264 @ 0xa33048e0] error while decoding MB 60 12, bytestream -7
May 09 21:03:46 orangepizero python[988]: [h264 @ 0xa33048e0] error while decoding MB 34 10, bytestream -9
May 09 21:03:46 orangepizero python[988]: [h264 @ 0xa33048e0] error while decoding MB 60 32, bytestream -5
May 09 21:02:53 orangepizero python[988]: [h264 @ 0xa33048e0] error while decoding MB 33 9, bytestream -7
May 09 21:02:38 orangepizero python[988]: [h264 @ 0xa33048e0] error while decoding MB 40 15, bytestream -5
May 09 21:02:37 orangepizero python[988]: [h264 @ 0xa33048e0] error while decoding MB 0 23, bytestream 1097
May 09 21:02:37 orangepizero python[988]: [h264 @ 0xa33048e0] left block unavailable for requested intra4x4 mode -1
May 09 21:01:51 orangepizero python[988]: [h264 @ 0xa33048e0] error while decoding MB 27 2, bytestream -15
May 09 21:00:51 orangepizero python[988]: [h264 @ 0xa33048e0] error while decoding MB 69 0, bytestream -41
May 09 20:59:49 orangepizero python[988]: [h264 @ 0xa33048e0] error while decoding MB 34 4, bytestream -15
May 09 20:58:49 orangepizero python[988]: [h264 @ 0xa33048e0] error while decoding MB 69 17, bytestream -15
May 09 20:55:45 orangepizero python[988]: [h264 @ 0xa33048e0] error while decoding MB 15 37, bytestream -5
May 09 20:54:43 orangepizero python[988]: [h264 @ 0xa33048e0] error while decoding MB 0 5, bytestream 4759
May 09 20:54:43 orangepizero python[988]: [h264 @ 0xa33048e0] left block unavailable for requested intra mode
May 09 20:53:41 orangepizero python[988]: [h264 @ 0xa33048e0] error while decoding MB 56 2, bytestream -21
May 09 20:52:40 orangepizero python[988]: [h264 @ 0xa33048e0] error while decoding MB 59 10, bytestream -5
May 09 20:52:37 orangepizero python[988]: [h264 @ 0xa33048e0] error while decoding MB 0 6, bytestream 7149
May 09 20:52:37 orangepizero python[988]: [h264 @ 0xa33048e0] left block unavailable for requested intra mode
May 09 20:49:37 orangepizero python[988]: [h264 @ 0xa33048e0] error while decoding MB 38 5, bytestream -7
May 09 20:49:24 orangepizero python[988]: [h264 @ 0xa33048e0] error while decoding MB 0 10, bytestream 3174
May 09 20:49:24 orangepizero python[988]: [h264 @ 0xa33048e0] left block unavailable for requested intra mode
May 09 20:48:30 orangepizero python[988]: [h264 @ 0xa33048e0] error while decoding MB 29 12, bytestream -5
May 09 20:47:34 orangepizero python[988]: [h264 @ 0xa33048e0] error while decoding MB 79 0, bytestream -9
May 09 20:47:34 orangepizero python[988]: [h264 @ 0xa33048e0] top block unavailable for requested intra mode -1
May 09 20:46:24 orangepizero python[988]: [h264 @ 0xa33048e0] error while decoding MB 0 5, bytestream 11936
May 09 20:46:24 orangepizero python[988]: [h264 @ 0xa33048e0] left block unavailable for requested intra mode
May 09 20:43:07 orangepizero python[988]: [h264 @ 0xa332c940] error while decoding MB 0 9, bytestream 25912
May 09 20:43:07 orangepizero python[988]: [h264 @ 0xa332c940] left block unavailable for requested intra4x4 mode -1
May 09 20:43:07 orangepizero python[988]: [h264 @ 0xa33048e0] error while decoding MB 0 16, bytestream -5
May 09 20:43:04 orangepizero python[988]: [h264 @ 0xa33048e0] error while decoding MB 0 9, bytestream 25912
May 09 20:43:04 orangepizero python[988]: [h264 @ 0xa33048e0] left block unavailable for requested intra4x4 mode -1
May 09 20:33:09 orangepizero python[988]: [h264 @ 0xa33048e0] error while decoding MB 58 1, bytestream -7
May 09 20:31:04 orangepizero python[988]: [h264 @ 0xa33048e0] error while decoding MB 69 0, bytestream -7
May 09 20:27:57 orangepizero python[988]: [h264 @ 0xa33048e0] error while decoding MB 49 5, bytestream -9
May 09 20:26:55 orangepizero python[988]: [h264 @ 0xa33048e0] error while decoding MB 0 5, bytestream 2067
May 09 20:26:55 orangepizero python[988]: [h264 @ 0xa33048e0] left block unavailable for requested intra mode
May 09 20:25:54 orangepizero python[988]: [h264 @ 0xa33048e0] error while decoding MB 72 0, bytestream -9
May 09 20:23:49 orangepizero python[988]: [h264 @ 0xa33048e0] error while decoding MB 8 4, bytestream -16
May 09 20:22:46 orangepizero python[988]: [h264 @ 0xa33048e0] error while decoding MB 70 0, bytestream -17
May 09 20:17:30 orangepizero python[988]: [h264 @ 0xa33048e0] error while decoding MB 74 6, bytestream -11
May 09 20:16:26 orangepizero python[988]: [h264 @ 0xa33048e0] error while decoding MB 77 0, bytestream -13
May 09 20:15:22 orangepizero python[988]: [h264 @ 0xa33048e0] error while decoding MB 72 9, bytestream -5
May 09 20:08:45 orangepizero python[988]: [h264 @ 0xa332ad90] error while decoding MB 0 6, bytestream 28667
May 09 20:08:45 orangepizero python[988]: [h264 @ 0xa332ad90] left block unavailable for requested intra mode
May 09 20:08:45 orangepizero python[988]: [h264 @ 0xa3331680] error while decoding MB 0 6, bytestream 28667
May 09 20:08:45 orangepizero python[988]: [h264 @ 0xa3331680] left block unavailable for requested intra mode
May 09 20:05:50 orangepizero python[988]: [h264 @ 0xa3331680] error while decoding MB 76 0, bytestream -17
May 09 19:56:42 orangepizero python[988]: [h264 @ 0xa3331680] error while decoding MB 73 0, bytestream -19
May 09 19:42:37 orangepizero python[988]: 2022-05-09 19:42:37,538 - camera - WARNING - Writing video frames queue exception <built-in method with_traceback of Full object at 0xa6e98b68>
May 09 19:42:32 orangepizero python[988]: OpenCV: FFMPEG: fallback to use tag 0x31637661/'avc1'
May 09 19:42:32 orangepizero python[988]: OpenCV: FFMPEG: tag 0x34363278/'x264' is not supported with codec id 27 and format 'mp4 / MP4 (MPEG-4 Part 14)'
May 09 19:21:24 orangepizero python[988]: OpenCV: FFMPEG: fallback to use tag 0x31637661/'avc1'
May 09 19:21:24 orangepizero python[988]: OpenCV: FFMPEG: tag 0x34363278/'x264' is not supported with codec id 27 and format 'mp4 / MP4 (MPEG-4 Part 14)'
May 09 19:15:38 orangepizero python[988]: 2022-05-09 19:15:38,506 - apscheduler.executors.default - INFO - Job "Notifier._send_print_start_info (trigger: date[2022-05-09 19:15:37 MSK], next run at: 2022-05-09 19:15:37 MSK)" executed successfully
May 09 19:15:37 orangepizero python[988]: 2022-05-09 19:15:37,220 - apscheduler.executors.default - INFO - Running job "Notifier._send_print_start_info (trigger: date[2022-05-09 19:15:37 MSK], next run at: 2022-05-09 19:15:37 MSK)" (scheduled at 2022-05-09 19:15:37.216325+03:00)
May 09 19:15:37 orangepizero python[988]: 2022-05-09 19:15:37,219 - apscheduler.scheduler - INFO - Removed job 58dcd1c482e0488fac4fc66102d2aec8
May 09 19:15:37 orangepizero python[988]: 2022-05-09 19:15:37,217 - apscheduler.scheduler - INFO - Added job "Notifier._send_print_start_info" to job store "default"
May 09 19:14:53 orangepizero python[988]: 2022-05-09 19:14:53,050 - apscheduler.scheduler - INFO - Removed job ws_reschedule
May 09 19:14:53 orangepizero python[988]: 2022-05-09 19:14:53,032 - apscheduler.executors.default - INFO - Job "reshedule (trigger: interval[0:00:02], next run at: 2022-05-09 19:14:55 MSK)" executed successfully
May 09 19:14:53 orangepizero python[988]: 2022-05-09 19:14:53,029 - apscheduler.executors.default - INFO - Running job "reshedule (trigger: interval[0:00:02], next run at: 2022-05-09 19:14:55 MSK)" (scheduled at 2022-05-09 19:14:53.024788+03:00)
May 09 19:14:51 orangepizero python[988]: 2022-05-09 19:14:51,026 - apscheduler.scheduler - INFO - Added job "reshedule" to job store "default"
May 09 19:14:49 orangepizero python[988]: 2022-05-09 19:14:49,714 - apscheduler.executors.default - INFO - Job "reshedule (trigger: interval[0:00:02], next run at: 2022-05-09 19:14:51 MSK)" executed successfully
May 09 19:14:49 orangepizero python[988]: 2022-05-09 19:14:49,710 - apscheduler.executors.default - INFO - Running job "reshedule (trigger: interval[0:00:02], next run at: 2022-05-09 19:14:49 MSK)" (scheduled at 2022-05-09 19:14:49.707010+03:00)
May 09 19:14:47 orangepizero python[988]: 2022-05-09 19:14:47,708 - apscheduler.scheduler - INFO - Added job "reshedule" to job store "default"
May 09 19:14:47 orangepizero python[988]: 2022-05-09 19:14:47,701 - __main__ - WARNING - klippy disconnect detected with message: notify_klippy_disconnected
May 09 18:21:03 orangepizero python[988]: 2022-05-09 18:21:03,161 - apscheduler.scheduler - INFO - Removed job ws_reschedule
May 09 18:21:03 orangepizero python[988]: 2022-05-09 18:21:03,130 - apscheduler.scheduler - INFO - Added job "reshedule" to job store "default"
May 09 18:21:02 orangepizero python[988]: 2022-05-09 18:21:02,445 - apscheduler.scheduler - INFO - Scheduler started
May 09 18:21:02 orangepizero python[988]: 2022-05-09 18:21:02,127 - apscheduler.scheduler - INFO - Scheduler started
May 09 18:20:42 orangepizero systemd[1]: Started Starts Moonraker Telegram Bot on startup.

### What branch does this occur on?

master

### Reports only on latest master or development branches!

- [X] I have updated to latest development/master version before submitting the bug

**Comment by ppcd9220** [comment]
Add on.
Video source is local network stream form IP camera:
rtsp://192.168.1.92/live/ch00_1
Codec: H.264

**Comment by aka13-404** [comment]
This is rather strange, and the bot does all the necessary checks which you mention already. It needs further testing, what specifically causes this issue with your stream. I'll get back to you when I have more information.
In the meantime, you could try a different format besides rtsp if your camera supports it.
