### ISSUE TITLE
Try to assemble timelapse is the print is cancelled

### ISSUE THREAD

**Issue by ppcd9220** [nlef/moonraker-telegram-bot#150]
### What would you like to see added?

If the print is cancelled (by klipper command, or through bot) time lapse is not assembled.
This is somehow the end of the print and assembly of timelapse should start, but this doesn't happen.

**Comment by aka13-404** [comment]
This is a good idea which we also had for a while.

**Comment by nlef** [comment]
a7ed7cdc9357cda6c2e546530051e75e2585888e
