### ISSUE TITLE
[Bug]: Klippy changed state to error pin XXX is reserved for serial  Once the underlying issue is corrected, use the "RESTART" command to reload the config and restart the host software. Printer is halted

### ISSUE THREAD

**Issue by Fuckingnameless** [nlef/moonraker-telegram-bot#155]
### What happened and in what context?

v1.4.3  

the bot starts this way but there´s no error on klipper, the pin isn´t even set on the .cfg file

also kiauh thrown an error about service not found when trying to restart the service?

### If needed, paste the relevant bot log contents here.

telegram-logs folder is empty

### If needed, paste the relevant bot journal contents here.

-- No entries --

### What branch does this occur on?

master

### Reports only on latest master or development branches!

- [X] I have updated to latest development/master version before submitting the bug

**Comment by aka13-404** [comment]
This has nothing to do with the bot. The bot only displays what it gets from moonraker. If you get such an error, such an error existst. My guess is, you have multiple instances and have messed up the installation, that's the reason for kiauh misbehaving as well.
