### ISSUE TITLE
[Bug]:  Installing Telegram bot moonraker from Kiauh

### ISSUE THREAD

**Issue by rdlvm** [nlef/moonraker-telegram-bot#159]
### What happened and in what context?

Error installing Telegram bot moonraker from Kiauh

### If needed, paste the relevant bot log contents here.

![imagen](https://i.ibb.co/3C3Y8Mq/photo-2022-05-23-13-15-23.jpg)

### What branch does this occur on?

master

### Reports only on latest master or development branches!

- [X] I have updated to latest development/master version before submitting the bug

**Comment by billyrittson** [comment]
I also encountered this bug last week, had to run the install.sh myself to finalize the install.
