### ISSUE TITLE
[Bug]: error during install "LPATH: unbound variable"

### ISSUE THREAD

**Issue by Benoit-LdL** [nlef/moonraker-telegram-bot#163]
### What happened and in what context?

When installing the plugin using the install script, after selecting the desired config path it gives an error: 

```
###### Telegram bot configuration file location selection


Enter the path for the configuration files location. Subfolders for multiple instances wil be created under this path. Its recommended to store it together with the klipper configuration for easier backup and usage.
Enter desired path: /home/pi/klipper_config
./scripts/install.sh: line 51: LPATH: unbound variable
```

### What branch does this occur on?

master

### Reports only on latest master or development branches!

- [X] I have updated to latest development/master version before submitting the bug

**Comment by flogal** [comment]
Same problem here :(

**Comment by yzheka** [comment]
Me too. Any workaround?

**Comment by flogal** [comment]
Thanks, the hotfix is working, i can install it now
