### ISSUE TITLE
[Bug]:  status_single_message not working

### ISSUE THREAD

**Issue by alexandrkut** [nlef/moonraker-telegram-bot#164]
### What happened and in what context?

I read news from 04 Feb 2022
`The most popular request got implemented - the preview and status messages are now updated in a single message. This is the new default behaviour. If you want to revert to the old behaviour, you can set the status_single_message: false in the [telegram_ui] section. We would appreciate your feedback on this, please let us know in the issue section.(https://github.com/nlef/moonraker-telegram-bot/issues/60)`

and add in telegram.conf
```
[telegram_ui]
status_single_message: false

```
after that i get warning message from bot
```
Unknown/bad items in section [telegram_ui]:
  status_single_message: false

Please correct the configuration according to the [wiki](https://github.com/nlef/moonraker-telegram-bot/wiki/Sample-config)
```

in sample config i not see option "status_single_message".

How i can get separate message on each update?

### What branch does this occur on?

master

### Reports only on latest master or development branches!

- [X] I have updated to latest development/master version before submitting the bug

**Comment by aka13-404** [comment]
You can not, it has been since removed. You can get notifications, when a status message has been updated via "silent_progress: false". Alternatively, you can roll back to that version of the bot, which is not supported anymore.
