### ISSUE TITLE
[Bug]: Additional status message info not showing

### ISSUE THREAD

**Issue by Disttrack** [nlef/moonraker-telegram-bot#166]
### What happened and in what context?

I have added several additional settings to the status message, but these are not displayed in the status message.

### If needed, paste the relevant bot log contents here.

![image](https://user-images.githubusercontent.com/66384045/172049278-59e85203-968f-40bc-aeef-b82df71aa8a8.png)
![image](https://user-images.githubusercontent.com/66384045/172049288-65cf6541-eca4-459b-a2c5-8d2cbd5e7796.png)
![image](https://user-images.githubusercontent.com/66384045/172049294-b6b1bb31-5c6d-445f-a119-f058f97dd06a.png)

### If needed, paste the relevant bot journal contents here.

[journalctl.log](https://github.com/nlef/moonraker-telegram-bot/files/8839905/journalctl.log)

### What branch does this occur on?

master

### Reports only on latest master or development branches!

- [X] I have updated to latest development/master version before submitting the bug

**Comment by nlef** [comment]
@Disttrack 
I can't figure out why it doesn't work from the attached log. Сoud you provide the complete single print bot log?

**Comment by Disttrack** [comment]
> @Disttrack I can't figure out why it doesn't work from the attached log. Сoud you provide the complete single print bot log?

I uninstalled the bot and reinstall It, now its working good. Thanks.
