### ISSUE TITLE
[Bug]: Bot able to connect to API but stuck at /access/login

### ISSUE THREAD

**Issue by coldyoungguy** [nlef/moonraker-telegram-bot#168]
### What happened and in what context?

Did not change anything to the bot.
Tried a different login credentials but does not work too.
Tried uninstalling and reinstalling and it did not work as well.
I have 2 other moonraker bots working on the same network just fine.
Not too sure if this is relevant but forced login on moonraker is set to true

### If needed, paste the relevant bot log contents here.

Traceback (most recent call last):
  File "/home/pi/moonraker-telegram-bot/bot/main.py", line 1400, in <module>
    klippy = Klippy(configWrap, light_power_device, psu_power_device, rotatingHandler)
  File "/home/pi/moonraker-telegram-bot/bot/klippy.py", line 84, in __init__
    self._auth_moonraker()
  File "/home/pi/moonraker-telegram-bot/bot/klippy.py", line 221, in _auth_moonraker
    json={"username": self._user, "password": self._passwd},
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.7/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.7/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.7/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.7/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /access/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x6544b930>: Failed to establish a new connection: [Errno 111] Connection refused'))
Stack (most recent call last):
  File "/home/pi/moonraker-telegram-bot/bot/main.py", line 54, in handle_exception
    stack_info=True,

### If needed, paste the relevant bot journal contents here.

-- Logs begin at Thu 2019-02-14 18:11:59 +08, end at Wed 2022-06-08 11:46:23 +08. --
Jun 08 11:46:18 ALICE-Voron2 systemd[1]: moonraker-telegram-bot.service: Failed with result 'exit-code'.
Jun 08 11:46:18 ALICE-Voron2 systemd[1]: moonraker-telegram-bot.service: Main process exited, code=exited, status=1/FAILURE
Jun 08 11:46:17 ALICE-Voron2 python[7186]:     stack_info=True,
Jun 08 11:46:17 ALICE-Voron2 python[7186]:   File "/home/pi/moonraker-telegram-bot/bot/main.py", line 54, in handle_exception
Jun 08 11:46:17 ALICE-Voron2 python[7186]: Stack (most recent call last):
Jun 08 11:46:17 ALICE-Voron2 python[7186]: requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /access/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection
Jun 08 11:46:17 ALICE-Voron2 python[7186]:     raise ConnectionError(e, request=request)
Jun 08 11:46:17 ALICE-Voron2 python[7186]:   File "/home/pi/moonraker-telegram-bot-env/lib/python3.7/site-packages/requests/adapters.py", line 519, in send
Jun 08 11:46:17 ALICE-Voron2 python[7186]:     r = adapter.send(request, **kwargs)
Jun 08 11:46:17 ALICE-Voron2 python[7186]:   File "/home/pi/moonraker-telegram-bot-env/lib/python3.7/site-packages/requests/sessions.py", line 645, in send
Jun 08 11:46:17 ALICE-Voron2 python[7186]:     resp = self.send(prep, **send_kwargs)
Jun 08 11:46:17 ALICE-Voron2 python[7186]:   File "/home/pi/moonraker-telegram-bot-env/lib/python3.7/site-packages/requests/sessions.py", line 529, in request
Jun 08 11:46:17 ALICE-Voron2 python[7186]:     return session.request(method=method, url=url, **kwargs)
Jun 08 11:46:17 ALICE-Voron2 python[7186]:   File "/home/pi/moonraker-telegram-bot-env/lib/python3.7/site-packages/requests/api.py", line 61, in request
Jun 08 11:46:17 ALICE-Voron2 python[7186]:     return request('post', url, data=data, json=json, **kwargs)
Jun 08 11:46:17 ALICE-Voron2 python[7186]:   File "/home/pi/moonraker-telegram-bot-env/lib/python3.7/site-packages/requests/api.py", line 117, in post
Jun 08 11:46:17 ALICE-Voron2 python[7186]:     json={"username": self._user, "password": self._passwd},
Jun 08 11:46:17 ALICE-Voron2 python[7186]:   File "/home/pi/moonraker-telegram-bot/bot/klippy.py", line 221, in _auth_moonraker
Jun 08 11:46:17 ALICE-Voron2 python[7186]:     self._auth_moonraker()
Jun 08 11:46:17 ALICE-Voron2 python[7186]:   File "/home/pi/moonraker-telegram-bot/bot/klippy.py", line 84, in __init__
Jun 08 11:46:17 ALICE-Voron2 python[7186]:     klippy = Klippy(configWrap, light_power_device, psu_power_device, rotatingHandler)
Jun 08 11:46:17 ALICE-Voron2 python[7186]:   File "/home/pi/moonraker-telegram-bot/bot/main.py", line 1400, in <module>
Jun 08 11:46:17 ALICE-Voron2 python[7186]: Traceback (most recent call last):
Jun 08 11:46:17 ALICE-Voron2 python[7186]: During handling of the above exception, another exception occurred:
Jun 08 11:46:17 ALICE-Voron2 python[7186]: urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /access/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection ob
Jun 08 11:46:17 ALICE-Voron2 python[7186]:     raise MaxRetryError(_pool, url, error or ResponseError(cause))
Jun 08 11:46:17 ALICE-Voron2 python[7186]:   File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
Jun 08 11:46:17 ALICE-Voron2 python[7186]:     _stacktrace=sys.exc_info()[2])
Jun 08 11:46:17 ALICE-Voron2 python[7186]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
Jun 08 11:46:17 ALICE-Voron2 python[7186]:     timeout=timeout
Jun 08 11:46:17 ALICE-Voron2 python[7186]:   File "/home/pi/moonraker-telegram-bot-env/lib/python3.7/site-packages/requests/adapters.py", line 450, in send
Jun 08 11:46:17 ALICE-Voron2 python[7186]: Traceback (most recent call last):
Jun 08 11:46:17 ALICE-Voron2 python[7186]: During handling of the above exception, another exception occurred:
Jun 08 11:46:17 ALICE-Voron2 python[7186]: urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x6540f8d0>: Failed to establish a new connection: [Errno 111] Connection refused
Jun 08 11:46:17 ALICE-Voron2 python[7186]:     self, "Failed to establish a new connection: %s" % e)
Jun 08 11:46:17 ALICE-Voron2 python[7186]:   File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 168, in _new_conn
Jun 08 11:46:17 ALICE-Voron2 python[7186]:     conn = self._new_conn()
Jun 08 11:46:17 ALICE-Voron2 python[7186]:   File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in connect
Jun 08 11:46:17 ALICE-Voron2 python[7186]:     self.connect()
Jun 08 11:46:17 ALICE-Voron2 python[7186]:   File "/usr/lib/python3.7/http/client.py", line 970, in send
Jun 08 11:46:17 ALICE-Voron2 python[7186]:     self.send(msg)
Jun 08 11:46:17 ALICE-Voron2 python[7186]:   File "/usr/lib/python3.7/http/client.py", line 1030, in _send_output
Jun 08 11:46:17 ALICE-Voron2 python[7186]:     self._send_output(message_body, encode_chunked=encode_chunked)
Jun 08 11:46:17 ALICE-Voron2 python[7186]:   File "/usr/lib/python3.7/http/client.py", line 1255, in endheaders
Jun 08 11:46:17 ALICE-Voron2 python[7186]:     self.endheaders(body, encode_chunked=encode_chunked)
Jun 08 11:46:17 ALICE-Voron2 python[7186]:   File "/usr/lib/python3.7/http/client.py", line 1306, in _send_request
Jun 08 11:46:17 ALICE-Voron2 python[7186]:     self._send_request(method, url, body, headers, encode_chunked)
Jun 08 11:46:17 ALICE-Voron2 python[7186]:   File "/usr/lib/python3.7/http/client.py", line 1260, in request
Jun 08 11:46:17 ALICE-Voron2 python[7186]:     conn.request(method, url, **httplib_request_kw)
Jun 08 11:46:17 ALICE-Voron2 python[7186]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
Jun 08 11:46:17 ALICE-Voron2 python[7186]:     chunked=chunked)
Jun 08 11:46:17 ALICE-Voron2 python[7186]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
Jun 08 11:46:17 ALICE-Voron2 python[7186]: Traceback (most recent call last):
Jun 08 11:46:17 ALICE-Voron2 python[7186]: During handling of the above exception, another exception occurred:

### What branch does this occur on?

master

### Reports only on latest master or development branches!

- [X] I have updated to latest development/master version before submitting the bug

**Comment by aka13-404** [comment]
Disable login/authorization, try again. If this helps, you have misconfigured moonraker and security.
