### ISSUE TITLE
[Bug]: Update manager shows Unknown instead of Up to Date

### ISSUE THREAD

**Issue by gurusonwheels** [nlef/moonraker-telegram-bot#175]
### What happened and in what context?

Update manager shows Unknown instead of Up to Date
see screenshot
![Screenshot 2022-06-13 at 13-43-23 Voron 2 2896](https://user-images.githubusercontent.com/3314914/173413122-258d7d54-a42b-4f31-aeb4-90f2cd881796.png)

### What branch does this occur on?

master

### Reports only on latest master or development branches!

- [X] I have updated to latest development/master version before submitting the bug

**Comment by Minsekt** [comment]
Same for me, happened after the update.

**Comment by aka13-404** [comment]
Update Manager is a moonraker feature. 
I'm leaving this open for now, but this is not on our side. If it's bothering you, run a reinstall. 
Not sure what happened here.

**Comment by gurusonwheels** [comment]
updated telegram today again . still your product is only one having trouble showing version . 
![Screenshot 2022-06-14 at 11-23-18 ERROR](https://user-images.githubusercontent.com/3314914/173615845-00ccd9e8-a811-4711-a11a-fe7b08dfd170.png)

**Comment by aka13-404** [comment]
Try it now, should be fine again. It's the version number which mainsail did not like, I have corrected it.

**Comment by gurusonwheels** [comment]
All good .
