### ISSUE TITLE
[Bug] tgalarm is broken? 

### ISSUE THREAD

**Issue by Fuckingnameless** [nlef/moonraker-telegram-bot#181]
### What happened and in what context?

title

### What branch does this occur on?

master

### Reports only on latest master or development branches!

- [X] I have updated to latest development/master version before submitting the bug

**Comment by aka13-404** [comment]
If you continue spamming nonsensical tickets, I will be forced to ban you from the repo.
Please respect our time and at least articulate, what is supposed to be broken for you.
