### ISSUE TITLE
 RESPOND PREFIX=tgnotify MSG not working

### ISSUE THREAD

**Issue by pertoft** [nlef/moonraker-telegram-bot#193]
Hi,

First of all, amazing work you are doring :-)

Next, i have been using the bot for a long time, but at some point the RESPOND command broke and the bot stopped presenting the messages on telegram from Klipper respond commands
Example from klipper:
`16:30:27 
$ RESPOND PREFIX=tgnotify MSG=my_message
16:30:27 
tgnotify my_message`

Shoud produce a telegram message, but nothing happens.

Everything else is working e.g. /status, /video, printer online etc. 

`pi@raspberrypi:~/klipper_config $ sudo journalctl -f -u moonraker-telegram-bot
-- Logs begin at Fri 2022-08-26 14:48:02 BST. --
Aug 26 15:29:25 raspberrypi python[6702]: 2022-08-26 15:29:25,804 - camera - WARNING - Reading video frames queue exception
Aug 26 15:29:25 raspberrypi python[6702]: 2022-08-26 15:29:25,916 - camera - WARNING - Reading video frames queue exception
Aug 26 15:29:26 raspberrypi python[6702]: 2022-08-26 15:29:26,033 - camera - WARNING - Reading video frames queue exception
Aug 26 15:29:26 raspberrypi python[6702]: 2022-08-26 15:29:26,126 - camera - WARNING - Reading video frames queue exception
Aug 26 15:29:26 raspberrypi python[6702]: 2022-08-26 15:29:26,237 - camera - WARNING - Reading video frames queue exception
Aug 26 15:30:07 raspberrypi systemd[1]: Stopping Starts Moonraker Telegram Bot on startup...
Aug 26 15:30:07 raspberrypi systemd[1]: moonraker-telegram-bot.service: Main process exited, code=killed, status=15/TERM
Aug 26 15:30:07 raspberrypi systemd[1]: moonraker-telegram-bot.service: Succeeded.
Aug 26 15:30:07 raspberrypi systemd[1]: Stopped Starts Moonraker Telegram Bot on startup.
Aug 26 15:30:07 raspberrypi systemd[1]: Started Starts Moonraker Telegram Bot on startup.
Aug 26 15:30:11 raspberrypi python[7408]: 2022-08-26 15:30:11,072 - camera - DEBUG -
Aug 26 15:30:11 raspberrypi python[7408]: General configuration for OpenCV 3.2.0 =====================================
Aug 26 15:30:11 raspberrypi python[7408]:   Version control:               unknown
Aug 26 15:30:11 raspberrypi python[7408]:   Extra modules:
Aug 26 15:30:11 raspberrypi python[7408]:     Location (extra):            /build/opencv-L65chJ/opencv-3.2.0+dfsg/contrib/modules
Aug 26 15:30:11 raspberrypi python[7408]:     Version control (extra):     unknown
Aug 26 15:30:11 raspberrypi python[7408]:   Platform:
Aug 26 15:30:11 raspberrypi python[7408]:     Timestamp:                   2019-02-12T11:26:31Z
Aug 26 15:30:11 raspberrypi python[7408]:     Host:                        Linux 4.4.0-124-generic armv8l
Aug 26 15:30:11 raspberrypi python[7408]:     CMake:                       3.13.4
Aug 26 15:30:11 raspberrypi python[7408]:     CMake generator:             Unix Makefiles
Aug 26 15:30:11 raspberrypi python[7408]:     CMake build tool:            /usr/bin/make
Aug 26 15:30:11 raspberrypi python[7408]:     Configuration:               Release
Aug 26 15:30:11 raspberrypi python[7408]:   C/C++:
Aug 26 15:30:11 raspberrypi python[7408]:     Built as dynamic libs?:      YES
Aug 26 15:30:11 raspberrypi python[7408]:     C++ Compiler:                /usr/bin/c++  (ver 8.2.0)
Aug 26 15:30:11 raspberrypi python[7408]:     C++ flags (Release):         -g -O2 -fdebug-prefix-map=/build/opencv-L65chJ/opencv-3.2.0+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-comment -fdiagnostics-show-option -pthread -fomit-frame-pointer -mfp16-format=ieee -ffunction-sections -fvisibility=hidden -fvisibility-inlines-hidden -g -O2 -fdebug-prefix-map=/build/opencv-L65chJ/opencv-3.2.0+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security  -DNDEBUG
Aug 26 15:30:11 raspberrypi python[7408]:     C++ flags (Debug):           -g -O2 -fdebug-prefix-map=/build/opencv-L65chJ/opencv-3.2.0+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-comment -fdiagnostics-show-option -pthread -fomit-frame-pointer -mfp16-format=ieee -ffunction-sections -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
Aug 26 15:30:11 raspberrypi python[7408]:     C Compiler:                  /usr/bin/cc
Aug 26 15:30:11 raspberrypi python[7408]:     C flags (Release):           -g -O2 -fdebug-prefix-map=/build/opencv-L65chJ/opencv-3.2.0+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wno-narrowing -Wno-comment -fdiagnostics-show-option -pthread -fomit-frame-pointer -mfp16-format=ieee -ffunction-sections -fvisibility=hidden -g -O2 -fdebug-prefix-map=/build/opencv-L65chJ/opencv-3.2.0+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security  -DNDEBUG
Aug 26 15:30:11 raspberrypi python[7408]:     C flags (Debug):             -g -O2 -fdebug-prefix-map=/build/opencv-L65chJ/opencv-3.2.0+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wno-narrowing -Wno-comment -fdiagnostics-show-option -pthread -fomit-frame-pointer -mfp16-format=ieee -ffunction-sections -fvisibility=hidden -g  -O0 -DDEBUG -D_DEBUG
Aug 26 15:30:11 raspberrypi python[7408]:     Linker flags (Release):      -Wl,-z,relro -Wl,-z,now -Wl,-z,relro -Wl,-z,now
Aug 26 15:30:11 raspberrypi python[7408]:     Linker flags (Debug):        -Wl,-z,relro -Wl,-z,now
Aug 26 15:30:11 raspberrypi python[7408]:     ccache:                      NO
Aug 26 15:30:11 raspberrypi python[7408]:     Precompiled headers:         NO
Aug 26 15:30:11 raspberrypi python[7408]:     Extra dependencies:          /usr/lib/arm-linux-gnueabihf/libwebp.so gdcmMSFF /usr/lib/arm-linux-gnueabihf/libImath.so /usr/lib/arm-linux-gnueabihf/libIlmImf.so /usr/lib/arm-linux-gnueabihf/libIex.so /usr/lib/arm-linux-gnueabihf/libHalf.so /usr/lib/arm-linux-gnueabihf/libIlmThread.so /usr/lib/libgdal.so gtk-3 gdk-3 pangocairo-1.0 pango-1.0 atk-1.0 cairo-gobject cairo gdk_pixbuf-2.0 gio-2.0 gobject-2.0 glib-2.0 gthread-2.0 dc1394 avcodec avformat avutil swscale avresample gphoto2 gphoto2_port /usr/lib/arm-linux-gnueabihf/hdf5/serial/libhdf5.so /usr/lib/arm-linux-gnueabihf/libpthread.so /usr/lib/arm-linux-gnueabihf/libsz.so /usr/lib/arm-linux-gnueabihf/libdl.so /usr/lib/arm-linux-gnueabihf/libm.so vtkRenderingOpenGL vtkImagingHybrid vtkIOImage vtkCommonDataModel vtkCommonMath vtkCommonCore vtksys vtkCommonMisc vtkCommonSystem vtkCommonTransforms vtkCommonExecutionModel vtkDICOMParser vtkIOCore /usr/lib/arm-linux-gnueabihf/libz.so vtkmetaio /usr/lib/arm-linux-gnueabihf/libjpeg.so /usr/lib/arm-linux-gnueabihf/libpng.so /usr/lib/arm-linux-gnueabihf/libtiff.so vtkImagingCore vtkRenderingCore vtkCommonColor vtkFiltersExtraction vtkFiltersCore vtkFiltersGeneral vtkCommonComputationalGeometry vtkFiltersStatistics vtkImagingFourier vtkalglib vtkFiltersGeometry vtkFiltersSources vtkInteractionStyle vtkRenderingLOD vtkFiltersModeling vtkIOPLY vtkIOGeometry vtkFiltersTexture vtkRenderingFreeType /usr/lib/arm-linux-gnueabihf/libfreetype.so vtkftgl vtkIOExport vtkRenderingAnnotation vtkImagingColor vtkRenderingContext2D vtkRenderingGL2PS vtkRenderingContextOpenGL /usr/lib/arm-linux-gnueabihf/libgl2ps.so vtkRenderingLabel tesseract lept dl m pthread rt tbb
Aug 26 15:30:11 raspberrypi python[7408]:     3rdparty dependencies:
Aug 26 15:30:11 raspberrypi python[7408]:   OpenCV modules:
Aug 26 15:30:11 raspberrypi python[7408]:     To be built:                 core flann hdf imgproc ml photo reg surface_matching video viz freetype fuzzy imgcodecs shape videoio highgui objdetect plot superres ts xobjdetect xphoto bgsegm bioinspired dpm face features2d line_descriptor saliency text calib3d ccalib datasets rgbd stereo stitching videostab ximgproc aruco optflow phase_unwrapping structured_light java python2 python3
Aug 26 15:30:11 raspberrypi python[7408]:     Disabled:                    world contrib_world
Aug 26 15:30:11 raspberrypi python[7408]:     Disabled by dependency:      tracking
Aug 26 15:30:11 raspberrypi python[7408]:     Unavailable:                 cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev cnn_3dobj cvv dnn matlab sfm
Aug 26 15:30:11 raspberrypi python[7408]:   GUI:
Aug 26 15:30:11 raspberrypi python[7408]:     QT:                          NO
Aug 26 15:30:11 raspberrypi python[7408]:     GTK+ 3.x:                    YES (ver 3.24.5)
Aug 26 15:30:11 raspberrypi python[7408]:     GThread :                    YES (ver 2.58.3)
Aug 26 15:30:11 raspberrypi python[7408]:     GtkGlExt:                    NO
Aug 26 15:30:11 raspberrypi python[7408]:     OpenGL support:              NO
Aug 26 15:30:11 raspberrypi python[7408]:     VTK support:                 YES (ver 6.3.0)
Aug 26 15:30:11 raspberrypi python[7408]:   Media I/O:
Aug 26 15:30:11 raspberrypi python[7408]:     ZLib:                        /usr/lib/arm-linux-gnueabihf/libz.so (ver 1.2.11)
Aug 26 15:30:11 raspberrypi python[7408]:     JPEG:                        /usr/lib/arm-linux-gnueabihf/libjpeg.so (ver )
Aug 26 15:30:11 raspberrypi python[7408]:     WEBP:                        /usr/lib/arm-linux-gnueabihf/libwebp.so (ver encoder: 0x020e)
Aug 26 15:30:11 raspberrypi python[7408]:     PNG:                         /usr/lib/arm-linux-gnueabihf/libpng.so (ver 1.6.36)
Aug 26 15:30:11 raspberrypi python[7408]:     TIFF:                        /usr/lib/arm-linux-gnueabihf/libtiff.so (ver 42 - 4.0.10)
Aug 26 15:30:11 raspberrypi python[7408]:     JPEG 2000:                   NO
Aug 26 15:30:11 raspberrypi python[7408]:     OpenEXR:                     /usr/lib/arm-linux-gnueabihf/libImath.so /usr/lib/arm-linux-gnueabihf/libIlmImf.so /usr/lib/arm-linux-gnueabihf/libIex.so /usr/lib/arm-linux-gnueabihf/libHalf.so /usr/lib/arm-linux-gnueabihf/libIlmThread.so (ver 2.2.1)
Aug 26 15:30:11 raspberrypi python[7408]:     GDAL:                        /usr/lib/libgdal.so
Aug 26 15:30:11 raspberrypi python[7408]:     GDCM:                        YES (ver 2.8.8)
Aug 26 15:30:11 raspberrypi python[7408]:   Video I/O:
Aug 26 15:30:11 raspberrypi python[7408]:     DC1394 1.x:                  NO
Aug 26 15:30:11 raspberrypi python[7408]:     DC1394 2.x:                  YES (ver 2.2.5)
Aug 26 15:30:11 raspberrypi python[7408]:     FFMPEG:                      YES
Aug 26 15:30:11 raspberrypi python[7408]:       avcodec:                   YES (ver 58.35.100)
Aug 26 15:30:11 raspberrypi python[7408]:       avformat:                  YES (ver 58.20.100)
Aug 26 15:30:11 raspberrypi python[7408]:       avutil:                    YES (ver 56.22.100)
Aug 26 15:30:11 raspberrypi python[7408]:       swscale:                   YES (ver 5.3.100)
Aug 26 15:30:11 raspberrypi python[7408]:       avresample:                YES (ver 4.0.0)
Aug 26 15:30:11 raspberrypi python[7408]:     GStreamer:                   NO
Aug 26 15:30:11 raspberrypi python[7408]:     OpenNI:                      NO
Aug 26 15:30:11 raspberrypi python[7408]:     OpenNI PrimeSensor Modules:  NO
Aug 26 15:30:11 raspberrypi python[7408]:     OpenNI2:                     NO
Aug 26 15:30:11 raspberrypi python[7408]:     PvAPI:                       NO
Aug 26 15:30:11 raspberrypi python[7408]:     GigEVisionSDK:               NO
Aug 26 15:30:11 raspberrypi python[7408]:     Aravis SDK:                  NO
Aug 26 15:30:11 raspberrypi python[7408]:     UniCap:                      NO
Aug 26 15:30:11 raspberrypi python[7408]:     UniCap ucil:                 NO
Aug 26 15:30:11 raspberrypi python[7408]:     V4L/V4L2:                    NO/YES
Aug 26 15:30:11 raspberrypi python[7408]:     XIMEA:                       NO
Aug 26 15:30:11 raspberrypi python[7408]:     Xine:                        NO
Aug 26 15:30:11 raspberrypi python[7408]:     gPhoto2:                     YES
Aug 26 15:30:11 raspberrypi python[7408]:   Parallel framework:            TBB (ver 2018.0 interface 10006)
Aug 26 15:30:11 raspberrypi python[7408]:   Other third-party libraries:
Aug 26 15:30:11 raspberrypi python[7408]:     Use IPP:                     NO
Aug 26 15:30:11 raspberrypi python[7408]:     Use VA:                      NO
Aug 26 15:30:11 raspberrypi python[7408]:     Use Intel VA-API/OpenCL:     NO
Aug 26 15:30:11 raspberrypi python[7408]:     Use Lapack:                  NO
Aug 26 15:30:11 raspberrypi python[7408]:     Use Eigen:                   YES (ver 3.3.7)
Aug 26 15:30:11 raspberrypi python[7408]:     Use Cuda:                    NO
Aug 26 15:30:11 raspberrypi python[7408]:     Use OpenCL:                  YES
Aug 26 15:30:11 raspberrypi python[7408]:     Use OpenVX:                  NO
Aug 26 15:30:11 raspberrypi python[7408]:     Use custom HAL:              NO
Aug 26 15:30:11 raspberrypi python[7408]:   OpenCL:                        <Dynamic loading of OpenCL library>
Aug 26 15:30:11 raspberrypi python[7408]:     Include path:                /usr/include/CL
Aug 26 15:30:11 raspberrypi python[7408]:     Use AMDFFT:                  NO
Aug 26 15:30:11 raspberrypi python[7408]:     Use AMDBLAS:                 NO
Aug 26 15:30:11 raspberrypi python[7408]:   Python 2:
Aug 26 15:30:11 raspberrypi python[7408]:     Interpreter:                 /usr/bin/python2.7 (ver 2.7.15)
Aug 26 15:30:11 raspberrypi python[7408]:     Libraries:                   /usr/lib/arm-linux-gnueabihf/libpython2.7.so (ver 2.7.15+)
Aug 26 15:30:11 raspberrypi python[7408]:     numpy:                       /usr/lib/python2.7/dist-packages/numpy/core/include (ver 1.16.1)
Aug 26 15:30:11 raspberrypi python[7408]:     packages path:               lib/python2.7/dist-packages
Aug 26 15:30:11 raspberrypi python[7408]:   Python 3:
Aug 26 15:30:11 raspberrypi python[7408]:     Interpreter:                 /usr/bin/python3 (ver 3.7.2)
Aug 26 15:30:11 raspberrypi python[7408]:     Libraries:                   /usr/lib/arm-linux-gnueabihf/libpython3.7m.so (ver 3.7.2+)
Aug 26 15:30:11 raspberrypi python[7408]:     numpy:                       /usr/lib/python3/dist-packages/numpy/core/include (ver 1.16.1)
Aug 26 15:30:11 raspberrypi python[7408]:     packages path:               lib/python3.7/dist-packages
Aug 26 15:30:11 raspberrypi python[7408]:   Python (for build):            /usr/bin/python2.7
Aug 26 15:30:11 raspberrypi python[7408]:   Java:
Aug 26 15:30:11 raspberrypi python[7408]:     ant:                         /usr/bin/ant (ver 1.10.5)
Aug 26 15:30:11 raspberrypi python[7408]:     JNI:                         /usr/lib/jvm/default-java/include /usr/lib/jvm/default-java/include/linux /usr/lib/jvm/default-java/include
Aug 26 15:30:11 raspberrypi python[7408]:     Java wrappers:               YES
Aug 26 15:30:11 raspberrypi python[7408]:     Java tests:                  NO
Aug 26 15:30:11 raspberrypi python[7408]:   Matlab:                        Matlab not found or implicitly disabled
Aug 26 15:30:11 raspberrypi python[7408]:   Documentation:
Aug 26 15:30:11 raspberrypi python[7408]:     Doxygen:                     /usr/bin/doxygen (ver 1.8.13)
Aug 26 15:30:11 raspberrypi python[7408]:   Tests and samples:
Aug 26 15:30:11 raspberrypi python[7408]:     Tests:                       NO
Aug 26 15:30:11 raspberrypi python[7408]:     Performance tests:           YES
Aug 26 15:30:11 raspberrypi python[7408]:     C/C++ Examples:              YES
Aug 26 15:30:11 raspberrypi python[7408]:   Install path:                  /usr
Aug 26 15:30:11 raspberrypi python[7408]:   cvconfig.h is in:              /build/opencv-L65chJ/opencv-3.2.0+dfsg/obj-arm-linux-gnueabihf
Aug 26 15:30:11 raspberrypi python[7408]: -----------------------------------------------------------------
Aug 26 15:30:11 raspberrypi python[7408]: 2022-08-26 15:30:11,087 - apscheduler.scheduler - INFO - Scheduler started
Aug 26 15:30:11 raspberrypi python[7408]: 2022-08-26 15:30:11,088 - apscheduler.scheduler - DEBUG - Looking for jobs to run
Aug 26 15:30:11 raspberrypi python[7408]: 2022-08-26 15:30:11,089 - apscheduler.scheduler - DEBUG - No jobs; waiting until a job is added
Aug 26 15:30:11 raspberrypi python[7408]: 2022-08-26 15:30:11,233 - apscheduler.scheduler - INFO - Scheduler started
Aug 26 15:30:11 raspberrypi python[7408]: 2022-08-26 15:30:11,234 - apscheduler.scheduler - DEBUG - Looking for jobs to run
Aug 26 15:30:11 raspberrypi python[7408]: 2022-08-26 15:30:11,236 - apscheduler.scheduler - DEBUG - No jobs; waiting until a job is added
Aug 26 15:30:11 raspberrypi python[7408]: 2022-08-26 15:30:11,480 - __main__ - ERROR - Uncaught exception
Aug 26 15:30:11 raspberrypi python[7408]: Traceback (most recent call last):
Aug 26 15:30:11 raspberrypi python[7408]:   File "/home/pi/moonraker-telegram-bot/bot/main.py", line 1443, in <module>
Aug 26 15:30:11 raspberrypi python[7408]:     greeting_message()
Aug 26 15:30:11 raspberrypi python[7408]:   File "/home/pi/moonraker-telegram-bot/bot/main.py", line 976, in greeting_message
Aug 26 15:30:11 raspberrypi python[7408]:     bot_updater.bot.set_my_commands(commands=prepare_commands_list(klippy.macros, configWrap.telegram_ui.include_macros_in_command_list))
Aug 26 15:30:11 raspberrypi python[7408]:   File "/home/pi/moonraker-telegram-bot-env/lib/python3.7/site-packages/telegram/bot.py", line 133, in decorator
Aug 26 15:30:11 raspberrypi python[7408]:     result = func(*args, **kwargs)
Aug 26 15:30:11 raspberrypi python[7408]:   File "/home/pi/moonraker-telegram-bot-env/lib/python3.7/site-packages/telegram/bot.py", line 5643, in set_my_commands
Aug 26 15:30:11 raspberrypi python[7408]:     result = self._post('setMyCommands', data, timeout=timeout, api_kwargs=api_kwargs)
Aug 26 15:30:11 raspberrypi python[7408]:   File "/home/pi/moonraker-telegram-bot-env/lib/python3.7/site-packages/telegram/bot.py", line 299, in _post
Aug 26 15:30:11 raspberrypi python[7408]:     f'{self.base_url}/{endpoint}', data=data, timeout=effective_timeout
Aug 26 15:30:11 raspberrypi python[7408]:   File "/home/pi/moonraker-telegram-bot-env/lib/python3.7/site-packages/telegram/utils/request.py", line 366, in post
Aug 26 15:30:11 raspberrypi python[7408]:     **urlopen_kwargs,
Aug 26 15:30:11 raspberrypi python[7408]:   File "/home/pi/moonraker-telegram-bot-env/lib/python3.7/site-packages/telegram/utils/request.py", line 279, in _request_wrapper
Aug 26 15:30:11 raspberrypi python[7408]:     raise BadRequest(message)
Aug 26 15:30:11 raspberrypi python[7408]: telegram.error.BadRequest: Bot_command_invalid
Aug 26 15:30:11 raspberrypi python[7408]: Stack (most recent call last):
Aug 26 15:30:11 raspberrypi python[7408]:   File "/home/pi/moonraker-telegram-bot/bot/main.py", line 67, in handle_exception
Aug 26 15:30:11 raspberrypi python[7408]:     stack_info=True,
`

**Comment by aka13-404** [comment]
Can you check with latest release please?

**Comment by blonestar** [comment]
Then it is an issue, the same one, I guess...
https://github.com/nlef/moonraker-telegram-bot/discussions/201
