### ISSUE TITLE
Status message rework, Secrets, QoL fixes

### ISSUE THREAD

**Issue by aka13-404** [nlef/moonraker-telegram-bot#196]
This update breaks the config (sorry). Please check out the release notes if you plan updating.
https://github.com/nlef/moonraker-telegram-bot/releases/tag/v1.4.5

**Comment by Grafton1046** [comment]
attempted to setup a secrets file, do the bot_token: and chat_id: fields sill need to exist in the telegram.conf file?

**Comment by aka13-404** [comment]
No, of course not, you can skip them in the main telegram.conf

**Comment by shcad** [comment]
Please add info to the Wiki that secret file MUST have [secrets] section header included to be parsed properly. Not only main config file.
Currently its not so obvious, and could be misleading (as for me to for a while).

BTW. Thank You for implementing

**Comment by aka13-404** [comment]
Oh man, I really did forget to add that, thank you for the catch.
It certainly is not obvious. Appreciate the effort, will fix it ASAP.
