### ISSUE TITLE
FR: Add additional information to status updates

### ISSUE THREAD

**Issue by zztopper** [nlef/moonraker-telegram-bot#20]
It'd be useful and convenient if you add the ETA to finish print into status updates which are sent on completion percentage and print height change

**Comment by zztopper** [comment]
Pls add also the absolute time left to print.

**Comment by nlef** [comment]
@zztopper  take a look at 9033d73f74578de18efbcab56e80935140cf548c

**Comment by zztopper** [comment]
Will do, I promise)
