### ISSUE TITLE
Add Bot to Telegramm Group or multi user

### ISSUE THREAD

**Issue by Secarius** [nlef/moonraker-telegram-bot#208]
Hi,
is it possible to add the bot to a telegram group or to invite a second telegram user to the bot?
I would like to have my mate to see the status and print updates too.

Thank you very much
Felix

**Comment by aka13-404** [comment]
Yes, refer to the documentation.
https://github.com/nlef/moonraker-telegram-bot/wiki/Sample-config#progress_notification
