### ISSUE TITLE
Bot online, no moonraker connection

### ISSUE THREAD

**Issue by Theodor2023** [nlef/moonraker-telegram-bot#234]
Bot writes:

Bot online, no moonraker connection!
 Connection failed. 
Failing...

But the printer works via fluidd.
The bot does not see it, although bot_token and chat_id are registered.
Help please)

**Comment by aka13-404** [comment]
I will ban you from the repo, if you insist on ignoring how to post issues and problems.

**Comment by Theodor2023** [comment]
Александр, прошу прощения, я здесь впервые, и не знаю всех правил.
[telegram.log](https://github.com/nlef/moonraker-telegram-bot/files/10289173/telegram.log)

**Comment by aka13-404** [comment]
> Александр, прошу прощения, я здесь впервые, и не знаю всех правил. [telegram.log](https://github.com/nlef/moonraker-telegram-bot/files/10289173/telegram.log)

Отлично, то что нужно. В сервере в логе указан адрес странный, надо бы просто localhost, можно с портом если он нестандартный.

**Comment by Theodor2023** [comment]
> > Александр, прошу прощения, я здесь впервые, и не знаю всех правил. [telegram.log](https://github.com/nlef/moonraker-telegram-bot/files/10289173/telegram.log)
> 
> Отлично, то что нужно. В сервере в логе указан адрес странный, надо бы просто localhost, можно с портом если он нестандартный.

Спасибо, я уже разобрался с этим. Целый день с клиппером мучаюсь, переходил с ноута на пишку, голова залилась. Теперь новая проблема, бот шлёт сообщения каждые 30 секунд. Видел что то тут подобное, но не понял как посмотреть решение)

**Comment by aka13-404** [comment]
Вся документация на https://github.com/nlef/moonraker-telegram-bot/wiki.
Бот шлет столько сообщений, сколько сконфигурировано :)
