### ISSUE TITLE
Allow taking an extra snapshot after the end gcode finished

### ISSUE THREAD

**Issue by jlsjonas** [nlef/moonraker-telegram-bot#244]
### What would you like to see added?

I'd love to see an extra parameter in timelapse auto mode to either wait until after the end gcode (+ motor destinations reached? ) And/or an arbitrary delay before taking the final snapshot.

Alternatively, allow a semi-auto mode that doesn't close the recording at the end, or a before finish after lapse gcode field to allow the same

Thanks for considering!

**Comment by aka13-404** [comment]
This is what the manual mode is for, I used to do the same thing you describe. 
Think of it as of [safe_z_home] and [homing_override] in Klipper. 
If you are not satisfied with the auto mode behaving a certain way, you can always extend it with the manual mode.
https://github.com/nlef/moonraker-telegram-bot/wiki/Interacting-with-klipper#controlling-timelapse-parameters-via-gcode

Switch to manual, add a` RESPOND PREFIX=timelapse MSG=start` to your start gcode, leave your automated settings like `height` or `time ` as they are, add a `RESPOND PREFIX=timelapse MSG=photo` to your end gcode, wherever you desire, followed by stop and create. 

We have no plans extending the automated mode in the foreseeable future.
