### ISSUE TITLE
Automate shutdown reason log sending on shutdown

### ISSUE THREAD

**Issue by zztopper** [nlef/moonraker-telegram-bot#247]
### What would you like to see added?

It'd be useful to extract latest config and shutdown reason on errors leading to Klipper shutdown and send as file to the user.

See [Klipper Docs](https://github.com/Klipper3d/klipper/blob/master/docs/Debugging.md#extracting-information-from-the-klippylog-file)

**Comment by nlef** [comment]
#294 is now more usefull
