### ISSUE TITLE
telegram bot stopps responding from time to time

### ISSUE THREAD

**Issue by maruhe** [nlef/moonraker-telegram-bot#248]
### What happened and in what context?

the telegram bot stopps responding from time to time
mostly while creating a timelapse
sometimes while printing
here the logs from today where it sopped updting while printing
more logs will follow with future crashes :-)

### If needed, paste the relevant bot log contents here.

*******************************************************************
Current Moonraker telegram bot config
[bot]
server = localhost

[camera]
host = http://localhost:8080/?action=stream

[progress_notification]
percent = 5
height = 0.5
time = 0

[timelapse]
manual_mode = true
cleanup = true
height = 0
time = 0
target_fps = 15
basedir = ~/moonraker-telegram-bot-timelapse
last_frame_duration = 5

[telegram_ui]
buttons = [status,pause,cancel,resume],[files,emergency,macros,shutdown],[CaseLight_0,CaseLight_1,CaseLight_5,CaseLight_10]
require_confirmation_macro = false
hidden_macros = Attach_Probe_Lock, Dock_Probe_UnlockDocks, G32, M300, PRINT_END, PRINT_START, status_busy, status_calibrating_z, status_cleaning, status_heating, status_homing, status_leveling, status_meshing, status_off, status_printing, status_ready, test_speed_fast, UPDATE_IDLE_TIMEOUT

....
teyt was to long for github
....

2023-01-25 21:46:40,954 - klippy - INFO - 'filename' has the same value as the current: 
2023-01-25 21:57:30,324 - websocket_helper - ERROR - Canceled by new editmessagemedia request
2023-01-25 21:57:41,373 - __main__ - ERROR - Job 9422b81a935c4e73bc53a8751a3a74b2 raisedCanceled by new editmessagemedia request
Traceback (most recent call last):
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/pi/moonraker-telegram-bot/bot/notifications.py", line 186, in _notify
    self._status_message.edit_media(media=InputMediaPhoto(photo))
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/message.py", line 2219, in edit_media
    return self.bot.edit_message_media(
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 133, in decorator
    result = func(*args, **kwargs)
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 2919, in edit_message_media
    return self._message(
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 202, in _message
    result = super()._message(
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 339, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 298, in _post
    return self.request.post(
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/utils/request.py", line 359, in post
    result = self._request_wrapper('POST', url, fields=data, **urlopen_kwargs)
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/utils/request.py", line 279, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Canceled by new editmessagemedia request
2023-01-25 21:58:13,084 - __main__ - ERROR - Job 4701b7baaa6241e8a4ec06e83c1fc302 raisedCanceled by new editmessagemedia request
Traceback (most recent call last):
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/pi/moonraker-telegram-bot/bot/notifications.py", line 186, in _notify
    self._status_message.edit_media(media=InputMediaPhoto(photo))
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/message.py", line 2219, in edit_media
    return self.bot.edit_message_media(
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 133, in decorator
    result = func(*args, **kwargs)
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 2919, in edit_message_media
    return self._message(
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 202, in _message
    result = super()._message(
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 339, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 298, in _post
    return self.request.post(
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/utils/request.py", line 359, in post
    result = self._request_wrapper('POST', url, fields=data, **urlopen_kwargs)
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/utils/request.py", line 279, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Canceled by new editmessagemedia request
2023-01-25 21:59:20,019 - __main__ - ERROR - Job d5aa91604d8c427aa112c8952051799e raisedCanceled by new editmessagemedia request
Traceback (most recent call last):
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/pi/moonraker-telegram-bot/bot/notifications.py", line 186, in _notify
    self._status_message.edit_media(media=InputMediaPhoto(photo))
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/message.py", line 2219, in edit_media
    return self.bot.edit_message_media(
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 133, in decorator
    result = func(*args, **kwargs)
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 2919, in edit_message_media
    return self._message(
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 202, in _message
    result = super()._message(
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 339, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 298, in _post
    return self.request.post(
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/utils/request.py", line 359, in post
    result = self._request_wrapper('POST', url, fields=data, **urlopen_kwargs)
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/utils/request.py", line 279, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Canceled by new editmessagemedia request
2023-01-25 22:01:00,909 - __main__ - ERROR - Job ae63fa94a6d8488983727d28e043349c raisedCanceled by new editmessagemedia request
Traceback (most recent call last):
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/pi/moonraker-telegram-bot/bot/notifications.py", line 186, in _notify
    self._status_message.edit_media(media=InputMediaPhoto(photo))
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/message.py", line 2219, in edit_media
    return self.bot.edit_message_media(
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 133, in decorator
    result = func(*args, **kwargs)
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 2919, in edit_message_media
    return self._message(
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 202, in _message
    result = super()._message(
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 339, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 298, in _post
    return self.request.post(
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/utils/request.py", line 359, in post
    result = self._request_wrapper('POST', url, fields=data, **urlopen_kwargs)
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/utils/request.py", line 279, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Canceled by new editmessagemedia request
2023-01-25 22:01:05,298 - klippy - INFO - 'filename' has the same value as the current: 

### If needed, paste the relevant bot journal contents here.

Jan 25 22:14:01 v1pi python[735]: 2023-01-25 22:14:01,471 - apscheduler.executors.default - INFO - Job "Notifier._notify (trigger: date[2023-01-25 22:13:59 CET], next run at: 2023-01-25 22:13:59 C>
Jan 25 22:13:59 v1pi python[735]: 2023-01-25 22:13:59,120 - apscheduler.executors.default - INFO - Running job "Notifier._notify (trigger: date[2023-01-25 22:13:59 CET], next run at: 2023-01-25 22>
Jan 25 22:13:59 v1pi python[735]: 2023-01-25 22:13:59,119 - apscheduler.scheduler - INFO - Removed job 9a79ed51dcc947de8a4162a6ce7a233f
Jan 25 22:13:59 v1pi python[735]: 2023-01-25 22:13:59,117 - apscheduler.scheduler - INFO - Added job "Notifier._notify" to job store "default"
Jan 25 22:13:12 v1pi python[735]: 2023-01-25 22:13:12,301 - apscheduler.executors.default - INFO - Job "Notifier._notify (trigger: date[2023-01-25 22:13:09 CET], next run at: 2023-01-25 22:13:09 C>
Jan 25 22:13:09 v1pi python[735]: 2023-01-25 22:13:09,976 - apscheduler.executors.default - INFO - Running job "Notifier._notify (trigger: date[2023-01-25 22:13:09 CET], next run at: 2023-01-25 22>
Jan 25 22:13:09 v1pi python[735]: 2023-01-25 22:13:09,976 - apscheduler.scheduler - INFO - Removed job d60bf7f8e1004f5e84271f7af6ae78be
Jan 25 22:13:09 v1pi python[735]: 2023-01-25 22:13:09,974 - apscheduler.scheduler - INFO - Added job "Notifier._notify" to job store "default"
Jan 25 22:12:03 v1pi python[735]: 2023-01-25 22:12:03,820 - apscheduler.executors.default - INFO - Job "Notifier._notify (trigger: date[2023-01-25 22:11:57 CET], next run at: 2023-01-25 22:11:57 C>
Jan 25 22:11:57 v1pi python[735]: 2023-01-25 22:11:57,531 - apscheduler.executors.default - INFO - Running job "Notifier._notify (trigger: date[2023-01-25 22:11:57 CET], next run at: 2023-01-25 22>
Jan 25 22:11:57 v1pi python[735]: 2023-01-25 22:11:57,530 - apscheduler.scheduler - INFO - Removed job cb5269f03c964366ab0aef5caa02eb42
Jan 25 22:11:57 v1pi python[735]: 2023-01-25 22:11:57,529 - apscheduler.scheduler - INFO - Added job "Notifier._notify" to job store "default"
Jan 25 22:11:34 v1pi python[735]: 2023-01-25 22:11:34,443 - apscheduler.executors.default - INFO - Job "Notifier._notify (trigger: date[2023-01-25 22:11:31 CET], next run at: 2023-01-25 22:11:31 C>
Jan 25 22:11:33 v1pi python[735]: 2023-01-25 22:11:33,408 - apscheduler.executors.default - INFO - Job "Notifier._notify (trigger: date[2023-01-25 22:11:31 CET], next run at: 2023-01-25 22:11:31 C>
Jan 25 22:11:31 v1pi python[735]: 2023-01-25 22:11:31,940 - apscheduler.executors.default - INFO - Running job "Notifier._notify (trigger: date[2023-01-25 22:11:31 CET], next run at: 2023-01-25 22>
Jan 25 22:11:31 v1pi python[735]: 2023-01-25 22:11:31,939 - apscheduler.scheduler - INFO - Removed job 9d52d240bd7c4e69ab15f717b066e32d
Jan 25 22:11:31 v1pi python[735]: 2023-01-25 22:11:31,939 - apscheduler.scheduler - INFO - Added job "Notifier._notify" to job store "default"
Jan 25 22:11:31 v1pi python[735]: 2023-01-25 22:11:31,193 - apscheduler.executors.default - INFO - Running job "Notifier._notify (trigger: date[2023-01-25 22:11:31 CET], next run at: 2023-01-25 22>
Jan 25 22:11:31 v1pi python[735]: 2023-01-25 22:11:31,192 - apscheduler.scheduler - INFO - Removed job 0a2a8316b01c477eb7af95b344c83719
Jan 25 22:11:31 v1pi python[735]: 2023-01-25 22:11:31,189 - apscheduler.scheduler - INFO - Added job "Notifier._notify" to job store "default"
Jan 25 22:11:25 v1pi python[735]: 2023-01-25 22:11:25,189 - apscheduler.executors.default - INFO - Job "Notifier._notify (trigger: date[2023-01-25 22:11:22 CET], next run at: 2023-01-25 22:11:22 C>
Jan 25 22:11:22 v1pi python[735]: 2023-01-25 22:11:22,167 - apscheduler.executors.default - INFO - Running job "Notifier._notify (trigger: date[2023-01-25 22:11:22 CET], next run at: 2023-01-25 22>
Jan 25 22:11:22 v1pi python[735]: 2023-01-25 22:11:22,166 - apscheduler.scheduler - INFO - Removed job 63044ad16e724144add645a5b285b904
Jan 25 22:11:22 v1pi python[735]: 2023-01-25 22:11:22,165 - apscheduler.scheduler - INFO - Added job "Notifier._notify" to job store "default"
Jan 25 22:09:00 v1pi python[735]: 2023-01-25 22:09:00,336 - apscheduler.executors.default - INFO - Job "Notifier._send_print_start_info (trigger: date[2023-01-25 22:08:58 CET], next run at: 2023-0>
Jan 25 22:08:58 v1pi python[735]: 2023-01-25 22:08:58,455 - apscheduler.executors.default - INFO - Running job "Notifier._send_print_start_info (trigger: date[2023-01-25 22:08:58 CET], next run at>
Jan 25 22:08:58 v1pi python[735]: 2023-01-25 22:08:58,454 - apscheduler.scheduler - INFO - Removed job 767074c8fc5948388f92c31b8497a2cd
Jan 25 22:08:58 v1pi python[735]: 2023-01-25 22:08:58,453 - apscheduler.scheduler - INFO - Added job "Notifier._send_print_start_info" to job store "default"
Jan 25 22:01:07 v1pi python[735]: 2023-01-25 22:01:07,498 - apscheduler.executors.default - INFO - Job "Timelapse._send_lapse (trigger: date[2023-01-25 22:01:07 CET], next run at: 2023-01-25 22:01>
Jan 25 22:01:07 v1pi python[735]: 2023-01-25 22:01:07,497 - apscheduler.executors.default - INFO - Running job "Timelapse._send_lapse (trigger: date[2023-01-25 22:01:07 CET], next run at: 2023-01->
Jan 25 22:01:07 v1pi python[735]: 2023-01-25 22:01:07,495 - apscheduler.scheduler - INFO - Removed job cde9383cc9064618a2a3207fa2bde59a
Jan 25 22:01:07 v1pi python[735]: 2023-01-25 22:01:07,494 - apscheduler.scheduler - INFO - Added job "Timelapse._send_lapse" to job store "default"
Jan 25 22:01:05 v1pi python[735]: 2023-01-25 22:01:05,581 - apscheduler.executors.default - INFO - Job "Notifier._send_message (trigger: date[2023-01-25 22:01:05 CET], next run at: 2023-01-25 22:0>
Jan 25 22:01:05 v1pi python[735]: 2023-01-25 22:01:05,304 - apscheduler.executors.default - INFO - Running job "Notifier._send_message (trigger: date[2023-01-25 22:01:05 CET], next run at: 2023-01>
Jan 25 22:01:05 v1pi python[735]: 2023-01-25 22:01:05,303 - apscheduler.scheduler - INFO - Removed job 8eb3191d79494e5abc7d34ad5c99d5da
Jan 25 22:01:05 v1pi python[735]: 2023-01-25 22:01:05,302 - apscheduler.scheduler - INFO - Added job "Notifier._send_message" to job store "default"
Jan 25 22:01:05 v1pi python[735]: 2023-01-25 22:01:05,298 - klippy - INFO - 'filename' has the same value as the current:
Jan 25 22:01:01 v1pi python[735]: 2023-01-25 22:01:01,494 - apscheduler.executors.default - INFO - Job "Notifier._notify (trigger: date[2023-01-25 22:00:57 CET], next run at: 2023-01-25 22:00:57 C>
Jan 25 22:01:00 v1pi python[735]: telegram.error.BadRequest: Canceled by new editmessagemedia request
Jan 25 22:01:00 v1pi python[735]:     raise BadRequest(message)
Jan 25 22:01:00 v1pi python[735]:   File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/utils/request.py", line 279, in _request_wrapper
Jan 25 22:01:00 v1pi python[735]:     result = self._request_wrapper('POST', url, fields=data, **urlopen_kwargs)
Jan 25 22:01:00 v1pi python[735]:   File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/utils/request.py", line 359, in post
Jan 25 22:01:00 v1pi python[735]:     return self.request.post(
Jan 25 22:01:00 v1pi python[735]:   File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 298, in _post
Jan 25 22:01:00 v1pi python[735]:     result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
Jan 25 22:01:00 v1pi python[735]:   File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 339, in _message
Jan 25 22:01:00 v1pi python[735]:     result = super()._message(
Jan 25 22:01:00 v1pi python[735]:   File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 202, in _message
Jan 25 22:01:00 v1pi python[735]:     return self._message(
Jan 25 22:01:00 v1pi python[735]:   File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 2919, in edit_message_media
Jan 25 22:01:00 v1pi python[735]:     result = func(*args, **kwargs)
Jan 25 22:01:00 v1pi python[735]:   File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 133, in decorator
Jan 25 22:01:00 v1pi python[735]:     return self.bot.edit_message_media(
Jan 25 22:01:00 v1pi python[735]:   File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/message.py", line 2219, in edit_media
Jan 25 22:01:00 v1pi python[735]:     self._status_message.edit_media(media=InputMediaPhoto(photo))
Jan 25 22:01:00 v1pi python[735]:   File "/home/pi/moonraker-telegram-bot/bot/notifications.py", line 186, in _notify
Jan 25 22:01:00 v1pi python[735]:     retval = job.func(*job.args, **job.kwargs)
Jan 25 22:01:00 v1pi python[735]:   File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
Jan 25 22:01:00 v1pi python[735]: Traceback (most recent call last):
Jan 25 22:01:00 v1pi python[735]: 2023-01-25 22:01:00,909 - __main__ - ERROR - Job ae63fa94a6d8488983727d28e043349c raisedCanceled by new editmessagemedia request
Jan 25 22:00:58 v1pi python[735]: 2023-01-25 22:00:58,098 - apscheduler.executors.default - INFO - Running job "Notifier._notify (trigger: date[2023-01-25 22:00:58 CET], next run at: 2023-01-25 22>
Jan 25 22:00:58 v1pi python[735]: 2023-01-25 22:00:58,098 - apscheduler.scheduler - INFO - Removed job ae63fa94a6d8488983727d28e043349c
Jan 25 22:00:58 v1pi python[735]: 2023-01-25 22:00:58,097 - apscheduler.scheduler - INFO - Added job "Notifier._notify" to job store "default"
Jan 25 22:00:57 v1pi python[735]: 2023-01-25 22:00:57,250 - apscheduler.executors.default - INFO - Running job "Notifier._notify (trigger: date[2023-01-25 22:00:57 CET], next run at: 2023-01-25 22>
Jan 25 22:00:57 v1pi python[735]: 2023-01-25 22:00:57,249 - apscheduler.scheduler - INFO - Removed job 6d58b7d30be14aecaa37c4caafec516f
Jan 25 22:00:57 v1pi python[735]: 2023-01-25 22:00:57,248 - apscheduler.scheduler - INFO - Added job "Notifier._notify" to job store "default"
Jan 25 22:00:43 v1pi python[735]: 2023-01-25 22:00:43,840 - apscheduler.executors.default - INFO - Job "Notifier._notify (trigger: date[2023-01-25 22:00:41 CET], next run at: 2023-01-25 22:00:41 C>
Jan 25 22:00:41 v1pi python[735]: 2023-01-25 22:00:41,559 - apscheduler.executors.default - INFO - Running job "Notifier._notify (trigger: date[2023-01-25 22:00:41 CET], next run at: 2023-01-25 22>
Jan 25 22:00:41 v1pi python[735]: 2023-01-25 22:00:41,559 - apscheduler.scheduler - INFO - Removed job b1013e7a5b414cd6a38fda0b36d48572
Jan 25 22:00:41 v1pi python[735]: 2023-01-25 22:00:41,557 - apscheduler.scheduler - INFO - Added job "Notifier._notify" to job store "default"
Jan 25 22:00:40 v1pi python[735]: 2023-01-25 22:00:40,098 - apscheduler.executors.default - INFO - Job "Notifier._notify (trigger: date[2023-01-25 22:00:35 CET], next run at: 2023-01-25 22:00:35 C>
Jan 25 22:00:35 v1pi python[735]: 2023-01-25 22:00:35,917 - apscheduler.executors.default - INFO - Running job "Notifier._notify (trigger: date[2023-01-25 22:00:35 CET], next run at: 2023-01-25 22>
Jan 25 22:00:35 v1pi python[735]: 2023-01-25 22:00:35,915 - apscheduler.scheduler - INFO - Removed job 7d490e9aa37a4c80ba207af00d377134
Jan 25 22:00:35 v1pi python[735]: 2023-01-25 22:00:35,911 - apscheduler.scheduler - INFO - Added job "Notifier._notify" to job store "default"
Jan 25 22:00:22 v1pi python[735]: 2023-01-25 22:00:22,260 - apscheduler.executors.default - INFO - Job "Notifier._notify (trigger: date[2023-01-25 22:00:19 CET], next run at: 2023-01-25 22:00:19 C>
Jan 25 22:00:19 v1pi python[735]: 2023-01-25 22:00:19,725 - apscheduler.executors.default - INFO - Running job "Notifier._notify (trigger: date[2023-01-25 22:00:19 CET], next run at: 2023-01-25 22>
Jan 25 22:00:19 v1pi python[735]: 2023-01-25 22:00:19,725 - apscheduler.scheduler - INFO - Removed job 70236d7ee3444185bdca04ad93b91bcb
Jan 25 22:00:19 v1pi python[735]: 2023-01-25 22:00:19,723 - apscheduler.scheduler - INFO - Added job "Notifier._notify" to job store "default"
Jan 25 22:00:09 v1pi python[735]: 2023-01-25 22:00:09,642 - apscheduler.executors.default - INFO - Job "Notifier._notify (trigger: date[2023-01-25 22:00:07 CET], next run at: 2023-01-25 22:00:07 C>
Jan 25 22:00:07 v1pi python[735]: 2023-01-25 22:00:07,478 - apscheduler.executors.default - INFO - Running job "Notifier._notify (trigger: date[2023-01-25 22:00:07 CET], next run at: 2023-01-25 22>
Jan 25 22:00:07 v1pi python[735]: 2023-01-25 22:00:07,477 - apscheduler.scheduler - INFO - Removed job c04eaf2c2941442a89361d39dad094f7
Jan 25 22:00:07 v1pi python[735]: 2023-01-25 22:00:07,475 - apscheduler.scheduler - INFO - Added job "Notifier._notify" to job store "default"
Jan 25 22:00:04 v1pi python[735]: 2023-01-25 22:00:04,288 - apscheduler.executors.default - INFO - Job "Notifier._notify (trigger: date[2023-01-25 22:00:01 CET], next run at: 2023-01-25 22:00:01 C>
Jan 25 22:00:01 v1pi python[735]: 2023-01-25 22:00:01,705 - apscheduler.executors.default - INFO - Running job "Notifier._notify (trigger: date[2023-01-25 22:00:01 CET], next run at: 2023-01-25 22>
Jan 25 22:00:01 v1pi python[735]: 2023-01-25 22:00:01,704 - apscheduler.scheduler - INFO - Removed job 35a5004fa8d9465388f2baded709d2a0
Jan 25 22:00:01 v1pi python[735]: 2023-01-25 22:00:01,703 - apscheduler.scheduler - INFO - Added job "Notifier._notify" to job store "default"
Jan 25 21:59:47 v1pi python[735]: 2023-01-25 21:59:47,517 - apscheduler.executors.default - INFO - Job "Notifier._notify (trigger: date[2023-01-25 21:59:44 CET], next run at: 2023-01-25 21:59:44 C>
Jan 25 21:59:46 v1pi python[735]: 2023-01-25 21:59:46,680 - apscheduler.executors.default - INFO - Job "Notifier._notify (trigger: date[2023-01-25 21:59:44 CET], next run at: 2023-01-25 21:59:44 C>
Jan 25 21:59:44 v1pi python[735]: 2023-01-25 21:59:44,908 - apscheduler.executors.default - INFO - Running job "Notifier._notify (trigger: date[2023-01-25 21:59:44 CET], next run at: 2023-01-25 21>
Jan 25 21:59:44 v1pi python[735]: 2023-01-25 21:59:44,908 - apscheduler.scheduler - INFO - Removed job 89b62d4ba5ee43d290c2b9302ec8d139

### What branch does this occur on?

master

### Reports only on latest master or development branches!

- [X] I have updated to latest development/master version before submitting the bug

**Comment by aka13-404** [comment]
Please post full logs. This is not helping to pinpoint your issue at all.

**Comment by maruhe** [comment]
[telegram.log](https://github.com/nlef/moonraker-telegram-bot/files/10561869/telegram.log)
here a full logfile (printer is currently printing) - it should countain several crashes - also a hang while printing and one while creating timelapse in the last 3-4 days

**Comment by maruhe** [comment]
clicking emergency-stop and then firmware_restart within a second seems to be a big problem for the telegram-bot also

**Comment by maruhe** [comment]
here it seems to just be unable to update the telegram-message
just hope the timelapse continues as I restarted the bot
[telegram.log](https://github.com/nlef/moonraker-telegram-bot/files/10856575/telegram.log)

**Comment by maruhe** [comment]
i control timlapse manual in gcode but after bot-restart no more picture was made and also no timelapse in the end

**Comment by aka13-404** [comment]
Stale, closing
