### ISSUE TITLE
Ability to send timelapses from moonraker-timelapse

### ISSUE THREAD

**Issue by haliknihudas666** [nlef/moonraker-telegram-bot#250]
### What would you like to see added?

[moonraker-timelapse](https://github.com/mainsail-crew/moonraker-timelapse) is a great timelapse plugin and very close to octolapse. This might be great timelapse integration since it has more control over the positioning of hotend and retraction settings.

My initial idea is to wait for moonraker-timelapse to finish and get the rendered video from its output folder then send it as timelapse to telegram

I'll try to contribute to this if have time to code 😃😁

**Comment by aka13-404** [comment]
Thank you for the suggestion.

We consider octolapse, as well as moonraker-timelapse subpar solutions. 
No software besides klipper has any business touching kinematics in the klipper ecosystem. 
The bot provides all tools to write necessary macros to execute macros and do custom timelapsing as the user desires.
This is, in our opinion, the proper way to do it. I am currently expanding the wiki with an example of such a macro setup by one of our users :). 

Nevertheless, we have coincidently added the possibility to upload video files to telegram, but we will neither accept pulls towards integration, nor integrate these projects ourselves.
