### ISSUE TITLE
Customizable Status Updates 

### ISSUE THREAD

**Issue by Grafton1046** [nlef/moonraker-telegram-bot#254]
Would it be possible to add a notification when the printer is paused, like when printing with an ERCF and there is a issue, the print gets paused and the time out changed. vs when the printer is paused via a regular pause command?

**Comment by aka13-404** [comment]
https://github.com/nlef/moonraker-telegram-bot/wiki/Interacting-with-klipper#send-custom-notifications-to-the-bot
It is already implemented. You can build a notification system as advanced as you wish. 
Simply add a one-liner to your pause g-code, or to your runout macro.
