### ISSUE TITLE
Video Livestream

### ISSUE THREAD

**Issue by Rec0iL** [nlef/moonraker-telegram-bot#259]
Would it be possible to make another function in addition to the /video command for example /stream
this should then start a call through telegram, and feed the webcam stream into the call. This way you could live monitor the print.

I don't know if this is a good idea or how difficult it is to realize, but I think it would be useful!

Thanks for considering it!

**Comment by aka13-404** [comment]
We thought about it, but sadly bots can't do calls. It's just not a thing in telegram :(
You'd have to do a "fake" account for the bot, for it to pretend to be a normal user, and run it via client api.
This would obv go against telegram ToS, so developing this would be an uphill battle.
