### ISSUE TITLE
A custom command for rendering timelapses

### ISSUE THREAD

**Issue by bakatrouble** [nlef/moonraker-telegram-bot#267]
### What would you like to see added?

I'm storing both my temp files and assembled timelapses on a network storage connected using NFS from a much more powerful machine than the one the bot is running on, and I'd like to leverage that power (and that would be much faster than transferring stuff over wifi over and over as well).

Would you be interested in accepting a PR implementing running a custom script for timelapse assembly?

**Comment by aka13-404** [comment]
I think it's safe to say that the PR is not coming/workaround was sufficient
