### ISSUE TITLE
[Bug]: Timelapse compilation error

### ISSUE THREAD

**Issue by DrDaveone** [nlef/moonraker-telegram-bot#279]
### What happened and in what context?

issue: не делает таймлапсы, по окончанию постит в тг Starting time-lapse assembly for *имя файла* и тишина, нагрузки цпу после этого не наблюдается.
камера с270, хост EEEPC 1001PX 2gb ram
Python 3.11.2, 6.1.0-9-amd64, Debian 6.1.27-1 
`appdirs==1.4.4
APScheduler==3.6.3
attrs==22.2.0
beautifulsoup4==4.11.2
beniget==0.4.1
blinker==1.5
Brotli==1.0.9
cachetools==4.2.2
certifi==2022.9.24
chardet==5.1.0
charset-normalizer==3.0.1
contourpy==1.0.7
cryptography==38.0.4
cycler==0.11.0
dbus-python==1.3.2
decorator==5.1.1
distlib==0.3.6
distro==1.8.0
emoji==2.2.0
filelock==3.9.0
fonttools==4.38.0
fs==2.4.16
gast==0.5.2
gevent==22.10.2
greenlet==2.0.2
html5lib==1.1
httplib2==0.20.4
idna==3.3
importlib-metadata==4.12.0
kiwisolver==0.0.0
lazr.restfulclient==0.14.5
lazr.uri==1.0.6
lxml==4.9.2
lz4==4.0.2+dfsg
matplotlib==3.6.3
more-itertools==8.10.0
mpmath==0.0.0
numpy==1.24.2
oauthlib==3.2.2
olefile==0.46
packaging==23.0
Pillow==9.5.0
platformdirs==2.6.0
ply==3.11
pycurl==7.45.2
PyGObject==3.42.2
PyJWT==2.6.0
pyparsing==3.0.9
PySimpleSOAP==1.16.2
PySocks==1.7.1
python-apt==2.6.0
python-dateutil==2.8.2
python-debian==0.1.49
python-debianbts==4.0.1
python-telegram-bot==13.15
pythran==0.11.0
pytz==2022.7.1
rel==0.4.8
reportbug==12.0.0
requests==2.30.0
scipy==1.10.1
six==1.16.0
soupsieve==2.3.2
sympy==1.11.1
tornado==6.1
tzlocal==2.1
ufoLib2==0.14.0
ujson==5.7.0
urllib3==1.26.12
virtualenv==20.17.1+ds
wadllib==1.3.6
webencodings==0.5.1
websocket-client==1.5.1
wsaccel==0.6.4
zipp==1.0.0
zope.event==4.4
zope.interface==5.5.2
`

### If needed, paste the relevant bot log contents here.

[telegram.log](https://github.com/nlef/moonraker-telegram-bot/files/11781558/telegram.log)

### What branch does this occur on?

development

### Reports only on latest master or development branches!

- [X] I have updated to latest development/master version before submitting the bug

**Comment by aka13-404** [comment]
Sorry, it is a bit stale, and we can not reproduce the behaviour. Open a new issue should your problem persist on 2.0.0
