### ISSUE TITLE
Can layer number be added to Status?

### ISSUE THREAD

**Issue by aModernGirlMakes** [nlef/moonraker-telegram-bot#280]
### What would you like to see added?

I did review the wiki and the sample config, but did not find this feature.

**Comment by PatrickGlatz** [comment]
I exactly wanted to ask the very same question +1

Should be configurable in
https://github.com/nlef/moonraker-telegram-bot/wiki/Sample-config#status_message_content

Perfect would be
Layer  :  14 of 122

Thanks for a short feedback

**Comment by QTreiber** [comment]
also interested in sending the layer number in status message...

**Comment by nlef** [comment]
@PhilBaz 
you could send custom message using gcode 
take a look at [wiki](https://github.com/nlef/moonraker-telegram-bot/wiki/Interacting-with-klipper#send-custom-notifications-to-the-bot)
