### ISSUE TITLE
[Bug]: AGAIN... moonraker-telegram-bot version cannot be parsed by Moonraker (or Mainsaill) 

### ISSUE THREAD

**Issue by cpasoft** [nlef/moonraker-telegram-bot#284]
### What happened and in what context?

The Moonraker Update Manager will show "? UNKNOWN" after an update to version v1.5-0-gb9b4703 & Mainsaill 2.6.1 or up.
@arksine has said that It looks like this could be a regression in Mainsail.

![256977863-7a482432-9931-4056-bdb2-702f8b00e9b9](https://github.com/nlef/moonraker-telegram-bot/assets/29692062/b4548ceb-1f7a-40ca-ba97-188bc0d1bd68)

Related to:
https://github.com/nlef/moonraker-telegram-bot/issues/253

### What branch does this occur on?

master

### Reports only on latest master or development branches!

- [X] I have updated to latest development/master version before submitting the bug

**Comment by mkryuchkov** [comment]
Any updates? May be workarounds?

**Comment by Phil1988** [comment]
Seems not yet updated...

**Comment by aka13-404** [comment]
Sorry, a bit stale, and can not reproduce. Please reopen if issue persists in 2.0.0
