### ISSUE TITLE
Potential issues with different timelapse types overlaps

### ISSUE THREAD

**Issue by aka13-404** [nlef/moonraker-telegram-bot#29]
As discussed, if different timelapse modes can individually control the lights, this will cause issues with status photos, as well as with timelapse itself, causing "blacked out" pictures.

**Comment by nlef** [comment]
fixed by 1ae13b31e17c930e734e9ca5493397b5227f2eb1 and 23f02ef8a8ad7fb010ac9e9120e7e8e3238081d4
@aka13-404 pls check!

**Comment by aka13-404** [comment]
In testing

**Comment by aka13-404** [comment]
Timelapse still causing issues, observing further

**Comment by aka13-404** [comment]
Fixed since 1.1.0
