### ISSUE TITLE
[Bug]: Bot keep restarting and spamming on SonicPad Debian

### ISSUE THREAD

**Issue by chipcian** [nlef/moonraker-telegram-bot#292]
### What happened and in what context?

After installing the bot via KIAUH and adding the configuration file with which it worked on the previous machine, the bot does not start on SonicPad Debian. He spams the "Printer Online" telegram several times a minute and does not respond to commands. Judging by the logs, I realized that it was restarting after some error. My Python version is 3.9.2

### If needed, paste the relevant bot log contents here.

[telegram.log](https://github.com/nlef/moonraker-telegram-bot/files/13299978/telegram.log)

### If needed, paste the relevant bot journal contents here.

-- Journal begins at Thu 2022-12-22 14:55:43 MSK, ends at Wed 2023-11-08 21:05:42 MSK. --
Nov 08 21:05:31 SonicPad systemd[1]: moonraker-telegram-bot.service: Failed with result 'signal'.
Nov 08 21:05:31 SonicPad systemd[1]: moonraker-telegram-bot.service: Main process exited, code=killed, status=4/ILL
Nov 08 21:05:31 SonicPad python[4615]: 2023-11-08 21:05:31,908 - websocket - INFO - Websocket connected
Nov 08 21:05:31 SonicPad python[4615]: 2023-11-08 21:05:31,896 - apscheduler.scheduler - INFO - Added job "WebSocketHelper.reshedule" to job store "default"
Nov 08 21:05:31 SonicPad python[4615]: 2023-11-08 21:05:31,191 - apscheduler.scheduler - INFO - Scheduler started
Nov 08 21:05:30 SonicPad python[4615]: 2023-11-08 21:05:30,685 - apscheduler.scheduler - INFO - Scheduler started
Nov 08 21:05:30 SonicPad python[4615]: 2023-11-08 21:05:30,662 - __main__ - ERROR -
Nov 08 21:05:25 SonicPad systemd[1]: Started Moonraker Telegram Bot SV1.
Nov 08 21:05:25 SonicPad systemd[1]: Stopped Moonraker Telegram Bot SV1.
Nov 08 21:05:25 SonicPad systemd[1]: moonraker-telegram-bot.service: Scheduled restart job, restart counter is at 32.
Nov 08 21:05:15 SonicPad systemd[1]: moonraker-telegram-bot.service: Failed with result 'signal'.
Nov 08 21:05:15 SonicPad systemd[1]: moonraker-telegram-bot.service: Main process exited, code=killed, status=4/ILL
Nov 08 21:05:15 SonicPad python[4570]: 2023-11-08 21:05:15,527 - websocket - INFO - Websocket connected
Nov 08 21:05:15 SonicPad python[4570]: 2023-11-08 21:05:15,517 - apscheduler.scheduler - INFO - Added job "WebSocketHelper.reshedule" to job store "default"
Nov 08 21:05:14 SonicPad python[4570]: 2023-11-08 21:05:14,897 - apscheduler.scheduler - INFO - Scheduler started
Nov 08 21:05:13 SonicPad python[4570]: 2023-11-08 21:05:13,099 - apscheduler.scheduler - INFO - Scheduler started
Nov 08 21:05:13 SonicPad python[4570]: 2023-11-08 21:05:13,073 - __main__ - ERROR -
Nov 08 21:05:07 SonicPad systemd[1]: Started Moonraker Telegram Bot SV1.
Nov 08 21:05:07 SonicPad systemd[1]: Stopped Moonraker Telegram Bot SV1.
Nov 08 21:05:07 SonicPad systemd[1]: moonraker-telegram-bot.service: Scheduled restart job, restart counter is at 31.
Nov 08 21:04:56 SonicPad systemd[1]: moonraker-telegram-bot.service: Failed with result 'signal'.
Nov 08 21:04:56 SonicPad systemd[1]: moonraker-telegram-bot.service: Main process exited, code=killed, status=4/ILL
Nov 08 21:04:56 SonicPad python[4548]: 2023-11-08 21:04:56,945 - websocket - INFO - Websocket connected
Nov 08 21:04:56 SonicPad python[4548]: 2023-11-08 21:04:56,933 - apscheduler.scheduler - INFO - Added job "WebSocketHelper.reshedule" to job store "default"
Nov 08 21:04:55 SonicPad python[4548]: 2023-11-08 21:04:55,162 - apscheduler.scheduler - INFO - Scheduler started
Nov 08 21:04:54 SonicPad python[4548]: 2023-11-08 21:04:54,858 - apscheduler.scheduler - INFO - Scheduler started
Nov 08 21:04:54 SonicPad python[4548]: 2023-11-08 21:04:54,832 - __main__ - ERROR -
Nov 08 21:04:49 SonicPad systemd[1]: Started Moonraker Telegram Bot SV1.
Nov 08 21:04:49 SonicPad systemd[1]: Stopped Moonraker Telegram Bot SV1.

### What branch does this occur on?

master

### Reports only on latest master or development branches!

- [X] I have updated to latest development/master version before submitting the bug

**Comment by aka13-404** [comment]
We do not support abominations as the sonicpad, sorry. 
Please contact your vendor.
