### ISSUE TITLE
Публикация лога

### ISSUE THREAD

**Issue by feadot** [nlef/moonraker-telegram-bot#294]
### What would you like to see added?

Наш друг и товарищ Андрей сделал анализатор лога клиппера https://coderus.openrepos.net/klipper_logs
Предлагаю сделать кнопку "заслать лог в анализатор и получить ссылку". Которую уже дальше и пересылать в просьбах о помощи или анализе лога.

**Comment by aka13-404** [comment]
Added in 2.0.0
