### ISSUE TITLE
[Bug]: ERROR:  Could not build wheels for ujson which use PEP 517 and cannot be installed directly

### ISSUE THREAD

**Issue by Nocentinia** [nlef/moonraker-telegram-bot#297]
### What happened and in what context?

I can't install the bot, compare this error
ERROR: Could not build wheels for ujson which use PEP 517 and cannot be installed directly

### What branch does this occur on?

development

### Reports only on latest master or development branches!

- [X] I have updated to latest development/master version before submitting the bug

**Comment by nlef** [comment]
@Nocentinia 
#313 should help you

**Comment by RunyAlfaNew** [comment]
I have a similar error:
"Could not build wheels for  wsaccel, wich is required to intsall pyproject.tom-based projects"

I have a fresh installation of Moonraker on Ubuntu 24

**Comment by brusarp** [comment]
> I have a similar error: "Could not build wheels for wsaccel, wich is required to intsall pyproject.tom-based projects"
> 
> I have a fresh installation of Moonraker on Ubuntu 24

Yea, me too... Same error...

**Comment by AlanAndre** [comment]
> > I have a similar error: "Could not build wheels for wsaccel, wich is required to intsall pyproject.tom-based projects"
> > I have a fresh installation of Moonraker on Ubuntu 24
> 
> Yea, me too... Same error...

For me the fix was updating `wsaccel==0.6.6` in `moonraker-telegram-bot/scripts/requirements.txt`
Using venv with Python 3.12.3.

**Comment by Tilitili** [comment]
> For me the fix was updating `wsaccel==0.6.6` in `moonraker-telegram-bot/scripts/requirements.txt` Using venv with Python 3.12.3.

Thank you. Everything works

**Comment by aka13-404** [comment]
This should be resolved in latest version. Reopen if not so.
