### ISSUE TITLE
Custom printer name setup in config

### ISSUE THREAD

**Issue by Hoeby** [nlef/moonraker-telegram-bot#301]
### What would you like to see added?

When the printer is started, the first message is "printer online".

I have multi printers, all with there own klipper environment. But also with there own hardware. Both give the first message "printer online"

Would like to modify the name "printer" so that i know which one is online.

Tried in mainsail to modify the printer name, but that isn't send in the telegram messages

**Comment by Altblechkutscher** [comment]
Don't you use individual bots? In my case, I have named the bot corresponding to my printer, which gives me a nice notification:

 ![image](https://github.com/nlef/moonraker-telegram-bot/assets/91900310/45c231d4-7bef-459d-b24f-3f6ae6ab2f5b)

**Comment by Hoeby** [comment]
No, i use 1 bot for all. It is also used for my home automation. This gives me all information in 1 bot view.

I know that i can't use the commands from telegram, to control the printer. Because more environments are lissening to the same bot. But i think that has nothing to do with the name "printer online"

**Comment by Altblechkutscher** [comment]
So if I've understood correctly, something like this?

![grafik](https://github.com/nlef/moonraker-telegram-bot/assets/91900310/45f096a3-2c76-42ef-934d-64083648a064)

![grafik](https://github.com/nlef/moonraker-telegram-bot/assets/91900310/b864d626-24d7-4f17-b3d6-b0a8f6ba1895)

![grafik](https://github.com/nlef/moonraker-telegram-bot/assets/91900310/8e8e8e03-a587-4a91-85d3-af4acb1adc22)

**Comment by Hoeby** [comment]
Yes, that is exactly the idea.

If i see it correctly, it is waiting for approve, to get merged?

**Comment by Hoeby** [comment]
Be aware that sending commands by telegram doesn't work then. If you are adware for this and don't use it, then it is no problem

**Comment by aka13-404** [comment]
We do not support and will never support multiple bots per instance. This is insanity, do you want to run one klipper/moonraker instance for multiple printers as well? All that to not create an additional bot via botfather? :D 

If you want to aggregate notifications in a single place, you can use a group, as suggested above.
Progress on control from a group will be tracked in #283. 

@Altblechkutscher You are welcome to open a PR request, this is a nice fun little option, if you think it has value. On our side nothing speaks

**Comment by Altblechkutscher** [comment]
@aka13-404 Indeed I did, which you can see here  #https://github.com/nlef/moonraker-telegram-bot/pull/302
