### ISSUE TITLE
This project seems to be abandoned

### ISSUE THREAD

**Issue by insane78** [nlef/moonraker-telegram-bot#306]
### What happened and in what context?

nothing to say...

### What branch does this occur on?

development

### Reports only on latest master or development branches!

- [X] I have updated to latest development/master version before submitting the bug

**Comment by owliwar** [comment]
Agree. one year with no commits to the master branches.. 
is the OP ok?

**Comment by nlef** [comment]
Hi all
Last year I had very little time for my open source projects.
As part of this year, I began to slowly transfer the bot to asyncio, which requires a complete refactoring of all the code.
I don't plan any major extensions or changes to the functionality of the bot only after the specified refactoring of the bot.
