### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by vic19765** [nlef/moonraker-telegram-bot#317]
### What happened and in what context?

The chat gpt say i need to see the moonraker-telegram-bot.py but i dont get it i alredy install again but nothing changed its all time getting the same error

### If needed, paste the relevant bot log contents here.

-- Logs begin at Sun 2024-07-21 02:17:07 PDT, end at Thu 2024-07-25 03:58:29 PDT
Jul 25 03:42:23 mkspi systemd[1]: moonraker-telegram-bot.service: Scheduled rest
Jul 25 03:42:23 mkspi systemd[1]: Stopped Moonraker Telegram Bot.
Jul 25 03:42:23 mkspi systemd[1]: Started Moonraker Telegram Bot.
Jul 25 03:42:23 mkspi python[5715]: /home/mks/moonraker-telegram-bot-env/bin/pyt
Jul 25 03:42:23 mkspi systemd[1]: moonraker-telegram-bot.service: Main process e
Jul 25 03:42:23 mkspi systemd[1]: moonraker-telegram-bot.service: Failed with re
Jul 25 03:42:23 mkspi systemd[1]: moonraker-telegram-bot.service: Service Restar
Jul 25 03:42:23 mkspi systemd[1]: moonraker-telegram-bot.service: Scheduled rest
Jul 25 03:42:23 mkspi systemd[1]: Stopped Moonraker Telegram Bot.
Jul 25 03:42:23 mkspi systemd[1]: moonraker-telegram-bot.service: Start request
Jul 25 03:42:23 mkspi systemd[1]: moonraker-telegram-bot.service: Failed with re
Jul 25 03:42:23 mkspi systemd[1]: Failed to start Moonraker Telegram Bot.
Jul 25 03:45:00 mkspi systemd[1]: Started Moonraker Telegram Bot.
Jul 25 03:45:00 mkspi python[5996]: /home/mks/moonraker-telegram-bot-env/bin/pyt
Jul 25 03:45:00 mkspi systemd[1]: moonraker-telegram-bot.service: Main process e
Jul 25 03:45:00 mkspi systemd[1]: moonraker-telegram-bot.service: Failed with re
Jul 25 03:45:00 mkspi systemd[1]: moonraker-telegram-bot.service: Service Restar
Jul 25 03:45:00 mkspi systemd[1]: moonraker-telegram-bot.service: Scheduled rest
Jul 25 03:45:00 mkspi systemd[1]: Stopped Moonraker Telegram Bot.
Jul 25 03:45:00 mkspi systemd[1]: Started Moonraker Telegram Bot.
Jul 25 03:45:00 mkspi python[5997]: /home/mks/moonraker-telegram-bot-env/bin/pyt
Jul 25 03:45:00 mkspi systemd[1]: moonraker-telegram-bot.service: Main process e
lines 1-23...skipping...
-- Logs begin at Sun 2024-07-21 02:17:07 PDT, end at Thu 2024-07-25 03:58:29 PD
Jul 25 03:42:23 mkspi systemd[1]: moonraker-telegram-bot.service: Scheduled res
Jul 25 03:42:23 mkspi systemd[1]: Stopped Moonraker Telegram Bot.
Jul 25 03:42:23 mkspi systemd[1]: Started Moonraker Telegram Bot.
Jul 25 03:42:23 mkspi python[5715]: /home/mks/moonraker-telegram-bot-env/bin/py
Jul 25 03:42:23 mkspi systemd[1]: moonraker-telegram-bot.service: Main process
Jul 25 03:42:23 mkspi systemd[1]: moonraker-telegram-bot.service: Failed with r
Jul 25 03:42:23 mkspi systemd[1]: moonraker-telegram-bot.service: Service Resta
Jul 25 03:42:23 mkspi systemd[1]: moonraker-telegram-bot.service: Scheduled res
Jul 25 03:42:23 mkspi systemd[1]: Stopped Moonraker Telegram Bot.
Jul 25 03:42:23 mkspi systemd[1]: moonraker-telegram-bot.service: Start request
Jul 25 03:42:23 mkspi systemd[1]: moonraker-telegram-bot.service: Failed with r
Jul 25 03:42:23 mkspi systemd[1]: Failed to start Moonraker Telegram Bot.
Jul 25 03:45:00 mkspi systemd[1]: Started Moonraker Telegram Bot.
Jul 25 03:45:00 mkspi python[5996]: /home/mks/moonraker-telegram-bot-env/bin/py
Jul 25 03:45:00 mkspi systemd[1]: moonraker-telegram-bot.service: Main process
Jul 25 03:45:00 mkspi systemd[1]: moonraker-telegram-bot.service: Failed with r
Jul 25 03:45:00 mkspi systemd[1]: moonraker-telegram-bot.service: Service Resta
Jul 25 03:45:00 mkspi systemd[1]: moonraker-telegram-bot.service: Scheduled res
Jul 25 03:45:00 mkspi systemd[1]: Stopped Moonraker Telegram Bot.
Jul 25 03:45:00 mkspi systemd[1]: Started Moonraker Telegram Bot.
Jul 25 03:45:00 mkspi python[5997]: /home/mks/moonraker-telegram-bot-env/bin/py
Jul 25 03:45:00 mkspi systemd[1]: moonraker-telegram-bot.service: Main process
Jul 25 03:45:00 mkspi systemd[1]: moonraker-telegram-bot.service: Failed with r
Jul 25 03:45:01 mkspi systemd[1]: moonraker-telegram-bot.service: Service Resta
Jul 25 03:45:01 mkspi systemd[1]: moonraker-telegram-bot.service: Scheduled res
Jul 25 03:45:01 mkspi systemd[1]: Stopped Moonraker Telegram Bot.
Jul 25 03:45:01 mkspi systemd[1]: Started Moonraker Telegram Bot.
Jul 25 03:45:01 mkspi python[5998]: /home/mks/moonraker-telegram-bot-env/bin/py
Jul 25 03:45:01 mkspi systemd[1]: moonraker-telegram-bot.service: Main process
Jul 25 03:45:01 mkspi systemd[1]: moonraker-telegram-bot.service: Failed with r
Jul 25 03:45:01 mkspi systemd[1]: moonraker-telegram-bot.service: Service Resta
Jul 25 03:45:01 mkspi systemd[1]: moonraker-telegram-bot.service: Scheduled res
Jul 25 03:45:01 mkspi systemd[1]: Stopped Moonraker Telegram Bot.
Jul 25 03:45:01 mkspi systemd[1]: Started Moonraker Telegram Bot.
Jul 25 03:45:01 mkspi python[5999]: /home/mks/moonraker-telegram-bot-env/bin/py
Jul 25 03:45:01 mkspi systemd[1]: moonraker-telegram-bot.service: Main process
lines 1-37...skipping...
-- Logs begin at Sun 2024-07-21 02:17:07 PDT, end at Thu 2024-07-25 03:58:29 PD
Jul 25 03:42:23 mkspi systemd[1]: moonraker-telegram-bot.service: Scheduled res
Jul 25 03:42:23 mkspi systemd[1]: Stopped Moonraker Telegram Bot.
Jul 25 03:42:23 mkspi systemd[1]: Started Moonraker Telegram Bot.
Jul 25 03:42:23 mkspi python[5715]: /home/mks/moonraker-telegram-bot-env/bin/py
Jul 25 03:42:23 mkspi systemd[1]: moonraker-telegram-bot.service: Main process
Jul 25 03:42:23 mkspi systemd[1]: moonraker-telegram-bot.service: Failed with r
Jul 25 03:42:23 mkspi systemd[1]: moonraker-telegram-bot.service: Service Resta
Jul 25 03:42:23 mkspi systemd[1]: moonraker-telegram-bot.service: Scheduled res
Jul 25 03:42:23 mkspi systemd[1]: Stopped Moonraker Telegram Bot.
Jul 25 03:42:23 mkspi systemd[1]: moonraker-telegram-bot.service: Start request
Jul 25 03:42:23 mkspi systemd[1]: moonraker-telegram-bot.service: Failed with r
Jul 25 03:42:23 mkspi systemd[1]: Failed to start Moonraker Telegram Bot.
Jul 25 03:45:00 mkspi systemd[1]: Started Moonraker Telegram Bot.
Jul 25 03:45:00 mkspi python[5996]: /home/mks/moonraker-telegram-bot-env/bin/py
Jul 25 03:45:00 mkspi systemd[1]: moonraker-telegram-bot.service: Main process
Jul 25 03:45:00 mkspi systemd[1]: moonraker-telegram-bot.service: Failed with r
Jul 25 03:45:00 mkspi systemd[1]: moonraker-telegram-bot.service: Service Resta
Jul 25 03:45:00 mkspi systemd[1]: moonraker-telegram-bot.service: Scheduled res
Jul 25 03:45:00 mkspi systemd[1]: Stopped Moonraker Telegram Bot.
Jul 25 03:45:00 mkspi systemd[1]: Started Moonraker Telegram Bot.
Jul 25 03:45:00 mkspi python[5997]: /home/mks/moonraker-telegram-bot-env/bin/py
Jul 25 03:45:00 mkspi systemd[1]: moonraker-telegram-bot.service: Main process
Jul 25 03:45:00 mkspi systemd[1]: moonraker-telegram-bot.service: Failed with r
Jul 25 03:45:01 mkspi systemd[1]: moonraker-telegram-bot.service: Service Resta
Jul 25 03:45:01 mkspi systemd[1]: moonraker-telegram-bot.service: Scheduled res
Jul 25 03:45:01 mkspi systemd[1]: Stopped Moonraker Telegram Bot.
Jul 25 03:45:01 mkspi systemd[1]: Started Moonraker Telegram Bot.
Jul 25 03:45:01 mkspi python[5998]: /home/mks/moonraker-telegram-bot-env/bin/py
Jul 25 03:45:01 mkspi systemd[1]: moonraker-telegram-bot.service: Main process
Jul 25 03:45:01 mkspi systemd[1]: moonraker-telegram-bot.service: Failed with r
Jul 25 03:45:01 mkspi systemd[1]: moonraker-telegram-bot.service: Service Resta
Jul 25 03:45:01 mkspi systemd[1]: moonraker-telegram-bot.service: Scheduled res
Jul 25 03:45:01 mkspi systemd[1]: Stopped Moonraker Telegram Bot.
Jul 25 03:45:01 mkspi systemd[1]: Started Moonraker Telegram Bot.
Jul 25 03:45:01 mkspi python[5999]: /home/mks/moonraker-telegram-bot-env/bin/py
Jul 25 03:45:01 mkspi systemd[1]: moonraker-telegram-bot.service: Main process
Jul 25 03:45:01 mkspi systemd[1]: moonraker-telegram-bot.service: Failed with r
Jul 25 03:45:02 mkspi systemd[1]: moonraker-telegram-bot.service: Service Resta
Jul 25 03:45:02 mkspi systemd[1]: moonraker-telegram-bot.service: Scheduled res
Jul 25 03:45:02 mkspi systemd[1]: Stopped Moonraker Telegram Bot.
Jul 25 03:45:02 mkspi systemd[1]: Started Moonraker Telegram Bot.
Jul 25 03:45:02 mkspi python[6010]: /home/mks/moonraker-telegram-bot-env/bin/py
Jul 25 03:45:02 mkspi systemd[1]: moonraker-telegram-bot.service: Main process
Jul 25 03:45:02 mkspi systemd[1]: moonraker-telegram-bot.service: Failed with r
Jul 25 03:45:02 mkspi systemd[1]: moonraker-telegram-bot.service: Service Resta
Jul 25 03:45:02 mkspi systemd[1]: moonraker-telegram-bot.service: Scheduled res
Jul 25 03:45:02 mkspi systemd[1]: Stopped Moonraker Telegram Bot.
Jul 25 03:45:02 mkspi systemd[1]: moonraker-telegram-bot.service: Start request
Jul 25 03:45:02 mkspi systemd[1]: moonraker-telegram-bot.service: Failed with r
lines 1-50...skipping...
-- Logs begin at Sun 2024-07-21 02:17:07 PDT, end at Thu 2024-07-25 03:58:29 PDT. --
Jul 25 03:42:23 mkspi systemd[1]: moonraker-telegram-bot.service: Scheduled restart job, restart counter is at 4.
Jul 25 03:42:23 mkspi systemd[1]: Stopped Moonraker Telegram Bot.
Jul 25 03:42:23 mkspi systemd[1]: Started Moonraker Telegram Bot.
Jul 25 03:42:23 mkspi python[5715]: /home/mks/moonraker-telegram-bot-env/bin/python: can't open file '/home/mks/moonraker-telegram-bot/moonraker-telegram-bot.py': [Errno 2] No such file or directory
Jul 25 03:42:23 mkspi systemd[1]: moonraker-telegram-bot.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 25 03:42:23 mkspi systemd[1]: moonraker-telegram-bot.service: Failed with result 'exit-code'.
Jul 25 03:42:23 mkspi systemd[1]: moonraker-telegram-bot.service: Service RestartSec=100ms expired, scheduling restart.
Jul 25 03:42:23 mkspi systemd[1]: moonraker-telegram-bot.service: Scheduled restart job, restart counter is at 5.
Jul 25 03:42:23 mkspi systemd[1]: Stopped Moonraker Telegram Bot.
Jul 25 03:42:23 mkspi systemd[1]: moonraker-telegram-bot.service: Start request repeated too quickly.
Jul 25 03:42:23 mkspi systemd[1]: moonraker-telegram-bot.service: Failed with result 'exit-code'.
Jul 25 03:42:23 mkspi systemd[1]: Failed to start Moonraker Telegram Bot.
Jul 25 03:45:00 mkspi systemd[1]: Started Moonraker Telegram Bot.
Jul 25 03:45:00 mkspi python[5996]: /home/mks/moonraker-telegram-bot-env/bin/python: can't open file '/home/mks/moonraker-telegram-bot/moonraker-telegram-bot.py': [Errno 2] No such file or directory
Jul 25 03:45:00 mkspi systemd[1]: moonraker-telegram-bot.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 25 03:45:00 mkspi systemd[1]: moonraker-telegram-bot.service: Failed with result 'exit-code'.
Jul 25 03:45:00 mkspi systemd[1]: moonraker-telegram-bot.service: Service RestartSec=100ms expired, scheduling restart.
Jul 25 03:45:00 mkspi systemd[1]: moonraker-telegram-bot.service: Scheduled restart job, restart counter is at 1.
Jul 25 03:45:00 mkspi systemd[1]: Stopped Moonraker Telegram Bot.
Jul 25 03:45:00 mkspi systemd[1]: Started Moonraker Telegram Bot.
Jul 25 03:45:00 mkspi python[5997]: /home/mks/moonraker-telegram-bot-env/bin/python: can't open file '/home/mks/moonraker-telegram-bot/moonraker-telegram-bot.py': [Errno 2] No such file or directory
Jul 25 03:45:00 mkspi systemd[1]: moonraker-telegram-bot.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 25 03:45:00 mkspi systemd[1]: moonraker-telegram-bot.service: Failed with result 'exit-code'.
Jul 25 03:45:01 mkspi systemd[1]: moonraker-telegram-bot.service: Service RestartSec=100ms expired, scheduling restart.
Jul 25 03:45:01 mkspi systemd[1]: moonraker-telegram-bot.service: Scheduled restart job, restart counter is at 2.
Jul 25 03:45:01 mkspi systemd[1]: Stopped Moonraker Telegram Bot.
Jul 25 03:45:01 mkspi systemd[1]: Started Moonraker Telegram Bot.
Jul 25 03:45:01 mkspi python[5998]: /home/mks/moonraker-telegram-bot-env/bin/python: can't open file '/home/mks/moonraker-telegram-bot/moonraker-telegram-bot.py': [Errno 2] No such file or directory
Jul 25 03:45:01 mkspi systemd[1]: moonraker-telegram-bot.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 25 03:45:01 mkspi systemd[1]: moonraker-telegram-bot.service: Failed with result 'exit-code'.
Jul 25 03:45:01 mkspi systemd[1]: moonraker-telegram-bot.service: Service RestartSec=100ms expired, scheduling restart.
Jul 25 03:45:01 mkspi systemd[1]: moonraker-telegram-bot.service: Scheduled restart job, restart counter is at 3.
Jul 25 03:45:01 mkspi systemd[1]: Stopped Moonraker Telegram Bot.
Jul 25 03:45:01 mkspi systemd[1]: Started Moonraker Telegram Bot.
Jul 25 03:45:01 mkspi python[5999]: /home/mks/moonraker-telegram-bot-env/bin/python: can't open file '/home/mks/moonraker-telegram-bot/moonraker-telegram-bot.py': [Errno 2] No such file or directory
Jul 25 03:45:01 mkspi systemd[1]: moonraker-telegram-bot.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 25 03:45:01 mkspi systemd[1]: moonraker-telegram-bot.service: Failed with result 'exit-code'.
Jul 25 03:45:02 mkspi systemd[1]: moonraker-telegram-bot.service: Service RestartSec=100ms expired, scheduling restart.
Jul 25 03:45:02 mkspi systemd[1]: moonraker-telegram-bot.service: Scheduled restart job, restart counter is at 4.
Jul 25 03:45:02 mkspi systemd[1]: Stopped Moonraker Telegram Bot.
Jul 25 03:45:02 mkspi systemd[1]: Started Moonraker Telegram Bot.
Jul 25 03:45:02 mkspi python[6010]: /home/mks/moonraker-telegram-bot-env/bin/python: can't open file '/home/mks/moonraker-telegram-bot/moonraker-telegram-bot.py': [Errno 2] No such file or directory
Jul 25 03:45:02 mkspi systemd[1]: moonraker-telegram-bot.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 25 03:45:02 mkspi systemd[1]: moonraker-telegram-bot.service: Failed with result 'exit-code'.
Jul 25 03:45:02 mkspi systemd[1]: moonraker-telegram-bot.service: Service RestartSec=100ms expired, scheduling restart.
Jul 25 03:45:02 mkspi systemd[1]: moonraker-telegram-bot.service: Scheduled restart job, restart counter is at 5.
Jul 25 03:45:02 mkspi systemd[1]: Stopped Moonraker Telegram Bot.
Jul 25 03:45:02 mkspi systemd[1]: moonraker-telegram-bot.service: Start request repeated too quickly.
Jul 25 03:45:02 mkspi systemd[1]: moonraker-telegram-bot.service: Failed with result 'exit-code'.
Jul 25 03:45:02 mkspi systemd[1]: Failed to start Moonraker Telegram Bot.
~
~
~
~
~
~
~
~
~
~
~
lines 1-51/51 (END)

### What branch does this occur on?

development

### Reports only on latest master or development branches!

- [X] I have updated to latest development/master version before submitting the bug

**Comment by nlef** [comment]
Most likely you used ChatGpt to modify the source code of the project.
Unfortunately, I can not help in this case and you need to find and fix the modification problems yourself
