### ISSUE TITLE
Add two-way confirmation for irreversible/dangerous actions

### ISSUE THREAD

**Issue by aka13-404** [nlef/moonraker-telegram-bot#32]
Buttons which cause irreversible actions, like "cancel print", or which might cause issue while printing, should have an interactive message with a confirmation button.

**Comment by nlef** [comment]
@aka13-404 check ab7d80de924f35dfc05f9d8e1a739cfc5cebe5c0

**Comment by aka13-404** [comment]
Confirmed as working
