### ISSUE TITLE
tgalarm makes printer freeze for a moment

### ISSUE THREAD

**Issue by yzheka** [nlef/moonraker-telegram-bot#320]
### What happened and in what context?

When I run `RESPOND PREFIX=tgalarm MSG="My message"` while the printer is printing something I see a small (~1 second) freeze of the printer's movements. This looks like network request for telegram api is made on the same thread as klipper's work.

### What branch does this occur on?

master

### Reports only on latest master or development branches!

- [X] I have updated to latest development/master version before submitting the bug

**Comment by aka13-404** [comment]
Can not reproduce on latest version, assume as fixed. Please reopen if you can reproduce.
