### ISSUE TITLE
[Bug]:auto-restrat

### ISSUE THREAD

**Issue by Matveiprokopew** [nlef/moonraker-telegram-bot#336]
### What happened and in what context?

The bot does not start,a cyclic reboot (auto-restart) does not allow it to start

### If needed, paste the relevant bot log contents here.

[moonraker.log](https://github.com/user-attachments/files/17689105/moonraker.log)

### What branch does this occur on?

master

### Reports only on latest master or development branches!

- [X] I have updated to latest development/master version before submitting the bug

**Comment by nlef** [comment]
This is not the bot installer script bug)
https://github.com/dw-0/kiauh/pull/600
