### ISSUE TITLE
moonraker authorization

### ISSUE THREAD

**Issue by breareros** [nlef/moonraker-telegram-bot#37]
При добавлении пользователей через fluidd и установке в mooraker.conf:

```
[authorization]
force_logins: true
```

бот не будет работать.
Прошу добавить авторизацию бота в moonraker по логину/паролю.

**Comment by DishersCave** [comment]
Не работает [timelapse]
Пробовал абсолютно разные настройки ...
текущий конфиг 

[timelapse]
basedir: /tmp/timelapse
copy_finished_timelapse_dir: /home/pi/timelapse/finished
cleanup: false
time: 5
target_fps: 15
manual_mode: false

p.s. файлы в папках не создает((

**Comment by nlef** [comment]
> 
> 
> Не работает [timelapse]
> Пробовал абсолютно разные настройки ...
> текущий конфиг
> 
> [timelapse]
> basedir: /tmp/timelapse
> copy_finished_timelapse_dir: /home/pi/timelapse/finished
> cleanup: false
> time: 5
> target_fps: 15
> manual_mode: false
> 
> p.s. файлы в папках не создает((

Как проблема с таймлапсом связана с авторизацией? Я создал отдельный issue для обсуждения)

**Comment by DishersCave** [comment]
Прошу прощения, не понял, что пишу как коммент, а не как новую тему )
