### ISSUE TITLE
Install script will break cinnamon desktop environments

### ISSUE THREAD

**Issue by th33xitus** [nlef/moonraker-telegram-bot#46]
This purge command just broke my cinnamon desktop environment on my development VM:
https://github.com/nlef/moonraker-telegram-bot/blob/c2c115b6c04a428806d2d034da4c1d0a03ad7307/scripts/install.sh#L60

That command will remove:
`blueman* cinnamon* python3-pil*`

![](http://puu.sh/Ienbz/da0ee46537.png)

I won't add the bot installer to KIAUH until that is fixed. I have to assume that this can also break other users systems. Im not going to risk that by distributing that script via KIAUH.

**Comment by aka13-404** [comment]
Alles klar, wird gemacht :D

**Comment by nlef** [comment]
@th33xitus 
here's fix 14063c3b75a79e1d3d7cb12ee201939666a687db

**Comment by th33xitus** [comment]
Fixed! 😄
Now my desktop environment stays alive hehe.

PR is also already merged 😄
