### ISSUE TITLE
Can't get a photo but video is working

### ISSUE THREAD

**Issue by Loreagle** [nlef/moonraker-telegram-bot#47]
Hello, I have the problem I can't get a photo sending the /photo command in bot chat. After the command I can see ">>>sending a photo" but then no photo is received. If I send /video the command is working fine.

Also all other commands are working fine, included macro, files and printer power on.

Any suggestion?

Thanks a lot

**Comment by nlef** [comment]
@Loreagle
Hi! pls look in bot log file ( /tmp/telegram.log is default location, maybe you configure another path)/ mqybe there are some errors?
maybe webp package is not installed in your system?

**Comment by Loreagle** [comment]
> @Loreagle Hi! pls look in bot log file ( /tmp/telegram.log is default location, maybe you configure another path)/ mqybe there are some errors? maybe webp package is not installed in your system?


I had the log in klipper_logs folder...  if webp package is not installed videos can work? I had a previous telegram bot and it was working, I uninstalled everything before installing your bot with kiauh

[telegram.txt](https://github.com/nlef/moonraker-telegram-bot/files/7315946/telegram.txt)

**Comment by Loreagle** [comment]
> @Loreagle you have problems with pillow deps. you may try setting low picture quality in camera section:
> 
> ```
> picture_quality: low
> #low - jpeg, quality 80. high - webp lossless
> ```

This worked! Thanks a lot :)
Is there any way to get high quality installing something? What can I do for pillow deps?

**Comment by Loreagle** [comment]
> > Thank you a lot! I'm using an Orange Pi PC Plus with Armbian 21.08.2 Buster
> 
> I tried some test environments, but i couldn't reproduce this bug. Could you try uninstalling python3-pill manualy and reinstall bot?
> 
> ```
> sudo apt remove python3-pil
> ```

Package "python3-pil" is not installed so was not removed.


> 
> > Just one last question... a friend of mine gets a gcode preview when printing starts but I get none... Is there something I'm missing on config? Looked into documentation but I can't see anything
> 
> thumbnails must be enabled in slicer and preview appears in fluidd & bot message.

I have thumbnails enabled in slicer and preview in fluidd but not on bot message

**Comment by nlef** [comment]
> Package "python3-pil" is not installed so was not removed.

try reinstall webp

```
sudo apt install libwebp libwebp-dev
```

After that, remove bot venv folder(${HOME}/moonraker-telegram-bot-env) and reinstall bot.

> I have thumbnails enabled in slicer and preview in fluidd but not on bot message

i;m sory, but preview in bot is webp image...

**Comment by minicom365** [comment]
I had the same problem.
I thought it would be weird because there was no problem with saving webp if Python tested the pillow directly .

Then I looked at the requirements.txt file in the installation script folder, and when I modified Pillow==8.4.0, it worked surprisingly.

**Comment by nlef** [comment]
> Then I looked at the requirements.txt file in the installation script folder, and when I modified Pillow==8.4.0, it worked surprisingly.

changing the version of the library is the same as reinstalling it. There is no information about changes regarding the webp in pillow release notes for 8.4.0.
maybe there were some problems during installation?

**Comment by minicom365** [comment]
I'm a beginner at code. I don't understand exactly, but when I look at the script, it seems to be installing a pillow in a Python virtual environment.
Before modifying the script, I installed and uninstalled pillow several times, but it didn't work, and the installation script only sent a message that it installed pillow 8.3.2.
I don't know what changes are in the pillow because of the lack of relevant knowledge, but in my case, the code worked only after changing it to 8.4.0.

**Comment by Loreagle** [comment]
> I'm a beginner at code. I don't understand exactly, but when I look at the script, it seems to be installing a pillow in a Python virtual environment. Before modifying the script, I installed and uninstalled pillow several times, but it didn't work, and the installation script only sent a message that it installed pillow 8.3.2. I don't know what changes are in the pillow because of the lack of relevant knowledge, but in my case, the code worked only after changing it to 8.4.0.

Hello, since I have the same problem can you please tell me how you modified the script to install 8.4.0? Thanks

**Comment by nlef** [comment]
@Loreagle @minicom365 
pls check new release

**Comment by Loreagle** [comment]
> @Loreagle @minicom365 
> pls check new release

Now it works! Thanks 😊
