### ISSUE TITLE
No timelapse at end

### ISSUE THREAD

**Issue by Dreded** [nlef/moonraker-telegram-bot#56]
Had a print recently end and instead of a time-lapse video I got this message...

> Images recoded 1380/3321

Any ideas?

**Comment by Dreded** [comment]
think I figured it out.. Pi overheated(timelapse is very cpu intensive) and im guessing the message above is just a progress indicator for long timelapse?

**Comment by nlef** [comment]
@Dreded 
It looks like your time-lapse is pretty big (lot's of photos). Try using a different codec for encoding video in camera settings 
```
[camera]
fourcc: mp4v
```
Message is informational and displays the process of building and sending the time-lapse
