### ISSUE TITLE
Alternative status messages via message pins/edits

### ISSUE THREAD

**Issue by aka13-404** [nlef/moonraker-telegram-bot#60]
A good addition would be to add a mode, where the bot does not send new status message for each update, but rather pins/edits a single message, which prevents notification spam, and allows the user to get more frequent, easier to track notifications, without getting spam in the bot chat. 

This should be an option to default new status-new message approach.
Additional thing to consider would be how this behaves with bot-groups.

**Comment by Ace768** [comment]
from the release info I cannot get it working the "old" way:

> The most popular request got implemented - the preview and status messages are now updated in a single message. This is the new default behaviour. If you want to revert to the old behaviour, you can set the status_single_message: false in the [telegram_ui] section. We would appreciate your feedback on this, please let us know in the issue section.(https://github.com/nlef/moonraker-telegram-bot/issues/60)>

I get the error it is unknown/bad
