### ISSUE TITLE
Add the possibility to run G-Codes or call a macro when the timelapse video is composed.

### ISSUE THREAD

**Issue by zztopper** [nlef/moonraker-telegram-bot#65]
If the timelapse video is greater than 50mb, it's not possible for bot to send it to telegram chat.
So that's why I want to send it to an external storage (cloud/local webserver, youtube etc) via shell script.
Shell script would take the timelapse file name with full path as an input parameter, and return the URL of the uploaded video, so that the bot could send the URL to the chat.

Sending timelapse video to the telegram chat as it is now should be optional, controlled with a param.
If the script name variable is not empty, script should be run after timelapse video is composed.

**Comment by nlef** [comment]
@zztopper 
pls check implementation dc9fbb0027400f3d762efabf9f65f765d3f20f22

**Comment by nlef** [comment]
9743669e45b44ec25e1aedc5fd7bed894f5dc34c adds saving lapse info into specific marco

**Comment by aka13-404** [comment]
Done in v1.4
