### ISSUE TITLE
Get Notification when printer shutdown

### ISSUE THREAD

**Issue by radaiko** [nlef/moonraker-telegram-bot#67]
It would be great if I get an notification when the printer was shutdown because of emergency.

Today I got a problem with on step stick and got no notification about it.

![image](https://user-images.githubusercontent.com/15850003/143920721-c1b46ffe-2126-4e86-aea1-b0a7c501ee9d.png)

**Comment by aka13-404** [comment]
Good idea, will be added it in the upcoming release(s).

**Comment by aka13-404** [comment]
Done in v1.4
