### ISSUE TITLE
Feature: option to send messages from macro

### ISSUE THREAD

**Issue by radaiko** [nlef/moonraker-telegram-bot#70]
I'm looking for a way to get a message when my filament runout, filament change macro is running or any other message I think is important for me to know

In my macros I have M117 messages so one way to have an option to get every M117 message per notification.
Any other option is me good aswell. 
I just want manual send important notifications.

**Comment by aka13-404** [comment]
Please read the documentation. 
This was implemented a long time ago. 
You can choose between notifications with or without sound, whichever suits you best.
https://github.com/nlef/moonraker-telegram-bot/blob/master/docs/interacting_with_klipper.md#custom-notifications
