### ISSUE TITLE
ETA does not update

### ISSUE THREAD

**Issue by Krakert** [nlef/moonraker-telegram-bot#79]
I was printing today with the bot in place and I noticed that the `Finish at` time does not update.
Mainsail ETA is lower than the bot reports. 

![Screenshot from 2022-01-05 15-57-01](https://user-images.githubusercontent.com/61704774/148238806-0ef8d54c-b106-4905-a5ad-19643b97ed1a.png)

Running the most simple config
```
[progress_notification]
percent: 100
```

**Comment by nlef** [comment]
We'll try to reproduce this and try to find the reason.

**Comment by Krakert** [comment]
It does update, but it does not come close to the ETA that Moonraker shows? Maybe it is based on the file? I know that there are more estimated "done" times.

![image](https://user-images.githubusercontent.com/61704774/148434749-377d013e-d480-4354-aeac-a59b8fc5462c.png)
Time went from 00:12 to 00:13

**Comment by aka13-404** [comment]
https://github.com/Klipper3d/klipper/blob/master/docs/Status_Reference.md#print_stats

Might be related M73/Displaystatus

**Comment by aka13-404** [comment]
@Krakert Would you kindly check if this persists in 1.4?

**Comment by Krakert** [comment]
Right now I'm setting up a new printer, when that's done I will setup the bot, a bit busy lately, but I will get to this! 

Great work guys!

**Comment by aka13-404** [comment]
Don't hesitate to reopen if the issue persists.
