### ISSUE TITLE
Option to config /status response 

### ISSUE THREAD

**Issue by Krakert** [nlef/moonraker-telegram-bot#80]
When you do `/status` you get the following output:

![image](https://user-images.githubusercontent.com/61704774/148435300-1d99c7ea-7d90-41c0-944a-9b332113bde2.png)

It would be nice to define that layout in the `telegram.conf`. Personally, I don't care about the filament usage and weight of the part (already checked in the slicer). I'm more interested in the layer height of the part, and maybe the total print time.

**Comment by aka13-404** [comment]
I myself would like that as well. As you understand, the needs of all the different users are different, so there propably has to be some templating, a la Jinja2, and that is quite the undertaking. We are looking into it, but don't expect it in the near future.

**Comment by Krakert** [comment]
Understandable! I really like the bot so far, really easy to set up!
Maybe I look into it myself in my free time, I like to contribute to the project. I already did some digging in the source code. 

Keep up the good work!

**Comment by aka13-404** [comment]
We would love seeing contributions from you. Glad you enjoy it!

**Comment by aka13-404** [comment]
Done in v1.4
